"""Tests for scripts/aid_emit1_validator.py — the AID-EMIT-1 conformance validator.

Vectors come from scripts/demo_edge_ingest.py --out (the emitter's exact
shape, signed), so the validator and the demo generator can't silently
drift apart. The pure-Python P-256 verifier is cross-checked against the
`cryptography` signer. Verifier-conformance cases follow AID-EMIT-1 §12:
accept the vectors; reject a flipped payload byte, a reordered record, a
swapped authority_uid, and a renumbered stream_seq.
"""

from __future__ import annotations

import copy
import importlib.util
import json
import pathlib
import subprocess
import sys

import pytest
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

_ROOT = pathlib.Path(__file__).resolve().parents[2]
_VALIDATOR = _ROOT / "scripts" / "aid_emit1_validator.py"

_spec = importlib.util.spec_from_file_location("aid_emit1_validator", _VALIDATOR)
validator = importlib.util.module_from_spec(_spec)
sys.modules["aid_emit1_validator"] = validator  # dataclasses needs the module registered
_spec.loader.exec_module(validator)


@pytest.fixture(scope="module")
def story(tmp_path_factory):
    """Signed four-record story + public key, generated by the demo script."""
    out = tmp_path_factory.mktemp("vectors") / "story"
    subprocess.run(
        [sys.executable, str(_ROOT / "scripts" / "demo_edge_ingest.py"), "--out", str(out)],
        check=True,
        capture_output=True,
    )
    records = [json.loads(line) for line in (out.parent / "story.jsonl").read_text().splitlines()]
    return records, out.parent / "story.jsonl", out.parent / "story.pub.pem"


def run(tmp_path, records, key=None, extra=()):
    """Run the validator's main() on records; return (exit_code, findings)."""
    path = tmp_path / "input.ndjson"
    path.write_text("\n".join(json.dumps(r) for r in records))
    report = tmp_path / "report.json"
    argv = [str(path), "--json", *extra]
    if key is not None:
        argv += ["--key", str(key)]
    import contextlib
    import io

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        code = validator.main(argv)
    report.write_text(buf.getvalue())
    return code, json.loads(buf.getvalue())["findings"]


def codes(findings):
    return {f["code"] for f in findings}


def test_clean_vectors_pass_with_signatures(tmp_path, story):
    records, _, key = story
    code, findings = run(tmp_path, records, key=key)
    assert code == 0
    assert not any(f["level"] == "ERROR" for f in findings)
    assert sum(1 for f in findings if f["code"] == "I-SIG-OK") == len(records)


def test_flipped_payload_byte_fails_fingerprint_and_signature(tmp_path, story):
    records, _, key = story
    tampered = copy.deepcopy(records)
    tampered[1]["disposition"] = "Denied"
    code, findings = run(tmp_path, tampered, key=key)
    assert code == 1
    assert {"E-FP-MISMATCH", "E-SIG-VERIFY"} <= codes(findings)


def test_swapped_authority_uid_fails(tmp_path, story):
    records, _, key = story
    tampered = copy.deepcopy(records)
    tampered[2]["attestation_list"][0]["authority_uid"] = "evil-org"
    code, findings = run(tmp_path, tampered, key=key)
    assert code == 1
    assert "E-FP-MISMATCH" in codes(findings)


def test_renumbered_stream_seq_is_tamper_not_just_gap(tmp_path, story):
    """Stamps ride inside the hashed bytes (§7): renumbering breaks the
    fingerprint, it doesn't merely open a gap."""
    records, _, key = story
    tampered = copy.deepcopy(records)
    tampered[3]["unmapped"]["cpex.stream"]["stream_seq"] = 9
    code, findings = run(tmp_path, tampered, key=key)
    assert code == 1
    assert {"E-FP-MISMATCH", "GAP-STREAM"} <= codes(findings)


def test_dropped_record_breaks_linkage_and_surfaces_gap(tmp_path, story):
    records, _, _ = story
    code, findings = run(tmp_path, records[:2] + records[3:])
    assert code == 1
    assert "E-CHAIN-UID" in codes(findings)
    assert "GAP-STREAM" in codes(findings)


def test_reordered_records_fail_chain_checks(tmp_path, story):
    records, _, _ = story
    code, findings = run(tmp_path, [records[0], records[2], records[1], records[3]])
    assert code == 1
    assert "E-CHAIN-UID" in codes(findings)


def test_duplicate_uid_is_idempotent_replay_warning(tmp_path, story):
    records, _, _ = story
    code, findings = run(tmp_path, records[:2] + [records[1]] + records[2:])
    assert code == 0
    assert "W-DUP-UID" in codes(findings)


def test_gap_becomes_error_with_strict_gaps(tmp_path, story):
    records, _, _ = story
    code, findings = run(tmp_path, records[:2] + records[3:], extra=("--strict-gaps",))
    assert code == 1
    assert any(f["code"] == "GAP-STREAM" and f["level"] == "ERROR" for f in findings)


def test_missing_record_integrity_profile_is_conformance_error(tmp_path, story):
    records, _, _ = story
    tampered = copy.deepcopy(records)
    tampered[0]["metadata"]["profiles"] = ["ai_operation", "security_control"]
    code, findings = run(tmp_path, tampered)
    assert code == 1
    assert "E-PROFILE" in codes(findings)


def test_wrong_key_fails_signature_verification(tmp_path, story):
    records, _, _ = story
    other = ec.generate_private_key(ec.SECP256R1())
    pem = other.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    wrong_key = tmp_path / "wrong.pub.pem"
    wrong_key.write_bytes(pem)
    code, findings = run(tmp_path, records, key=wrong_key)
    assert code == 1
    assert sum(1 for f in findings if f["code"] == "E-SIG-VERIFY") == len(records)


def test_trust_base_sample_passes_integrity_checks(tmp_path):
    sample = (
        _ROOT
        / "docs"
        / "cosai-ws4-ocsf-mapping"
        / "trust-base-inventory-sample"
        / "agent-trust-base-inventory.sample.ndjson"
    )
    records = [json.loads(line) for line in sample.read_text().splitlines()]
    code, findings = run(tmp_path, records)
    assert code == 0
    assert "W-CLASS" in codes(findings)  # class checks skipped, integrity applied


def test_pure_python_verifier_matches_cryptography_signer():
    key = ec.generate_private_key(ec.SECP256R1())
    pem = key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    point = validator.load_p256_public_key(pem.decode())
    message = validator.dsse_pae(b'{"class_uid":6003}')
    signature = key.sign(message, ec.ECDSA(hashes.SHA256()))
    assert validator.ecdsa_p256_sha256_verify(point, message, signature)
    assert not validator.ecdsa_p256_sha256_verify(point, message + b"x", signature)
    assert not validator.ecdsa_p256_sha256_verify(point, message, signature[:-4] + bytes(4))


def test_covered_bytes_matches_demo_signing_input(story):
    """The validator's §4 rule and the demo's sign-time rule agree byte-for-byte."""
    records, _, _ = story
    for record in records:
        recomputed = validator.hashlib.sha256(validator.covered_bytes(record)).hexdigest()
        assert recomputed == record["attestation_list"][0]["fingerprint"]["value"]


def test_base64_signature_is_validated(tmp_path, story):
    records, _, key = story
    tampered = copy.deepcopy(records)
    tampered[0]["unmapped"]["signature_b64"] = "!!not-base64!!"
    code, findings = run(tmp_path, tampered, key=key)
    assert code == 1
    assert "E-SIG-B64" in codes(findings)


def test_der_helpers_reject_garbage():
    with pytest.raises(ValueError):
        validator.load_p256_public_key("not a pem")
    assert not validator.ecdsa_p256_sha256_verify((validator.GX, validator.GY), b"m", b"\x30\x00")
    with pytest.raises(ValueError):
        validator.parse_der_signature(b"\x02\x01\x01")


def test_json_output_shape(tmp_path, story):
    records, path, _ = story
    import contextlib
    import io

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        code = validator.main([str(path), "--json"])
    payload = json.loads(buf.getvalue())
    assert code == 0
    assert payload["records"] == len(records)
    assert payload["pass"] is True
