/**
 * AISummaryPanel — slide-out drawer showing AI-generated audit summary.
 *
 * Renders a Perplexity-powered markdown summary of agent activity with
 * metadata (model used, events analysed) and a regenerate action.
 */

import Markdown from 'react-markdown'
import type { AuditSummaryResponse } from '../../types/api'

// ── Component ────────────────────────────────────────────────────

interface Props {
  data: AuditSummaryResponse | null
  loading: boolean
  error: string | null
  onClose: () => void
  onRegenerate: () => void
}

export function AISummaryPanel({ data, loading, error, onClose, onRegenerate }: Props) {
  return (
    <>
      {/* Backdrop */}
      <div className="fixed inset-0 bg-black/50 z-40" onClick={onClose} />

      {/* Drawer */}
      <div className="fixed right-0 top-0 bottom-0 w-full max-w-xl bg-zinc-900 border-l border-zinc-700 z-50 overflow-y-auto shadow-2xl animate-slide-in flex flex-col">
        {/* Header */}
        <div className="sticky top-0 bg-zinc-900/95 backdrop-blur border-b border-zinc-700 px-6 py-4 flex items-center justify-between z-10">
          <div className="flex items-center gap-3">
            <span className="text-lg">✨</span>
            <h2 className="text-lg font-semibold text-zinc-100">AI Analysis</h2>
            {data && (
              <span className="text-xs text-zinc-500 bg-zinc-800 px-2 py-0.5 rounded">
                {data.events_analyzed} events · {data.model_used}
              </span>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-zinc-400 hover:text-zinc-200 rounded transition-colors"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              className="h-5 w-5"
            >
              <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 px-6 py-5">
          {loading && (
            <div className="flex flex-col items-center justify-center py-20 text-zinc-400 gap-3">
              <div className="h-8 w-8 border-2 border-purple-400 border-t-transparent rounded-full animate-spin" />
              <p className="text-sm">Analyzing audit activity...</p>
              <p className="text-xs text-zinc-500">This usually takes 5–10 seconds</p>
            </div>
          )}

          {error && (
            <div className="bg-red-500/5 border border-red-500/20 rounded-lg p-5 text-center">
              <p className="text-sm text-red-400 mb-3">{error}</p>
              {error.includes('Pro') ? (
                <a
                  href="/settings"
                  className="inline-flex px-4 py-2 text-sm font-medium text-zinc-100 bg-purple-500/90 hover:bg-purple-400/90 rounded-lg transition-colors"
                >
                  Upgrade Plan
                </a>
              ) : (
                <button
                  onClick={onRegenerate}
                  className="px-4 py-2 text-sm font-medium text-zinc-300 bg-zinc-800 hover:bg-zinc-700 rounded-lg transition-colors border border-zinc-600"
                >
                  Try Again
                </button>
              )}
            </div>
          )}

          {data && !loading && !error && (
            <div className="prose prose-invert prose-sm max-w-none prose-headings:text-zinc-100 prose-p:text-zinc-300 prose-li:text-zinc-300 prose-strong:text-zinc-200 prose-a:text-purple-400 prose-a:no-underline hover:prose-a:underline prose-code:text-purple-300 prose-code:bg-zinc-800 prose-code:px-1 prose-code:py-0.5 prose-code:rounded">
              <Markdown>{data.summary}</Markdown>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-zinc-900/95 backdrop-blur border-t border-zinc-700 px-6 py-3 flex items-center justify-between">
          <p className="text-xs text-zinc-500">
            Generated by AI. Verify findings against raw audit data.
          </p>
          {data && !loading && (
            <button
              onClick={onRegenerate}
              className="px-3 py-1.5 text-xs font-medium text-zinc-300 bg-zinc-800 hover:bg-zinc-700 rounded-lg transition-colors border border-zinc-600"
            >
              Regenerate
            </button>
          )}
        </div>
      </div>
    </>
  )
}
