"""Ada menu-bar app — native macOS status-bar launcher for Ada.

Architecture:
  Launch Ada.app/Contents/MacOS/launcher
    → exec venv python this_file (bundled in Contents/Resources/)
      → subprocess.Popen(serve.py)  [stdout+stderr piped to rotating log]
      → rumps event loop            [status-bar icon, 5-s health poll, menus]

Agent dir is resolved relative to this script's bundle path; falls back to
the canonical dev checkout /Users/jeffleva/Dev/AI-Identity/agent.

Logs: ~/Library/Logs/Ada/ada.log  (5 MB rotating, 3 backups).
"""

from __future__ import annotations

import logging
import signal
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from logging.handlers import RotatingFileHandler
from pathlib import Path

try:
    import rumps
except ImportError:
    sys.exit(
        "rumps is not installed.\n"
        "Run: agent/.venv/bin/pip install rumps\n"
        "Or:  bash agent/launcher/build_launcher.sh --menubar  (handles this automatically)"
    )

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PORT = 8000
URL = f"http://127.0.0.1:{PORT}"
# serve.py exposes /healthz (ADK also mounts /health, but /healthz is canonical).
HEALTH_URL = f"{URL}/healthz"

STATUS_STARTING = "⏳"
STATUS_RUNNING = "✓"
STATUS_STOPPED = "✗"

# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def _find_agent_dir() -> Path:
    """Locate the agent/ directory regardless of where the .app bundle lives.

    Search order:
    1. Parent of this file's directory if it contains serve.py + .venv
       (running from agent/launcher/ in a dev checkout).
    2. Bundle-relative: Contents/Resources/ → up 3 → .app's sibling repo/agent/.
    3. Canonical hardcoded dev path (last-resort fallback matching .command).
    """
    here = Path(__file__).resolve().parent

    candidates = [
        here.parent,  # dev: agent/launcher/../ = agent/
        here,  # dev: running from agent/ itself
        here.parent.parent.parent / "agent",  # bundle: Resources/../../.. = .app/..
        here.parent.parent.parent.parent / "agent",  # one nesting level deeper
        Path("/Users/jeffleva/Dev/AI-Identity/agent"),  # canonical fallback
    ]

    for c in candidates:
        c = c.resolve()
        if (c / "serve.py").exists() and (c / ".venv" / "bin" / "python").exists():
            return c

    return Path("/Users/jeffleva/Dev/AI-Identity/agent")


AGENT_DIR = _find_agent_dir()
VENV_PY = AGENT_DIR / ".venv" / "bin" / "python"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

LOG_DIR = Path.home() / "Library" / "Logs" / "Ada"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = LOG_DIR / "ada.log"

_log_handler = RotatingFileHandler(str(LOG_PATH), maxBytes=5 * 1024 * 1024, backupCount=3)
_log_handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
logging.basicConfig(handlers=[_log_handler], level=logging.INFO)
log = logging.getLogger("ada.menubar")


def _pipe_to_log(pipe: object, level: int = logging.INFO) -> None:
    """Read lines from a subprocess pipe and forward them to the rotating log."""
    server_log = logging.getLogger("ada.serve")
    try:
        for raw in pipe:  # type: ignore[union-attr]
            server_log.log(level, raw.rstrip())
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Icon
# ---------------------------------------------------------------------------


def _find_icon() -> str | None:
    """Return path to a menu-bar icon, generating a minimal PNG if needed.

    Preference order:
    1. ada_menubar.png in the same directory (pre-generated by build_launcher.sh).
    2. ada.icns in the same directory (NSImage can load .icns directly).
    3. Generate a minimal 44×44 @2x PNG via Pillow as last resort.
    """
    here = Path(__file__).resolve().parent
    for p in [here / "ada_menubar.png", here / "ada.icns"]:
        if p.exists():
            return str(p)

    try:
        from PIL import Image, ImageDraw  # noqa: PLC0415

        size = 44  # @2x for Retina
        img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        draw.rounded_rectangle((0, 0, size - 1, size - 1), radius=9, fill=(139, 92, 246, 255))
        # Simple white "A" triangle + crossbar
        cx = size // 2
        draw.polygon(
            [(cx, 5), (size - 7, size - 7), (7, size - 7)],
            outline=(255, 255, 255, 220),
        )
        draw.line([(12, size - 17), (size - 12, size - 17)], fill=(255, 255, 255, 220), width=2)
        out = here / "ada_menubar.png"
        img.save(str(out), "PNG")
        return str(out)
    except Exception as exc:
        log.warning("Could not generate menu-bar icon: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Server process manager
# ---------------------------------------------------------------------------


class ServerManager:
    """Owns the serve.py subprocess.  Thread-safe start / stop / restart."""

    def __init__(self) -> None:
        self._proc: subprocess.Popen | None = None
        self._lock = threading.Lock()

    # ------------------------------------------------------------------ start

    def start(self) -> None:
        with self._lock:
            if self._proc and self._proc.poll() is None:
                return  # already running
            if not VENV_PY.exists():
                log.error(
                    "venv python not found at %s — cannot start serve.py.\n"
                    "Set up the venv: cd %s && python3.11 -m venv .venv && "
                    ".venv/bin/pip install -r requirements.txt",
                    VENV_PY,
                    AGENT_DIR,
                )
                return
            log.info("Starting serve.py (agent_dir=%s, py=%s)", AGENT_DIR, VENV_PY)
            try:
                proc = subprocess.Popen(
                    [str(VENV_PY), "serve.py", "--port", str(PORT)],
                    cwd=str(AGENT_DIR),
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
                self._proc = proc
                # Forward serve.py output to the rotating log via daemon threads.
                threading.Thread(
                    target=_pipe_to_log, args=(proc.stdout, logging.INFO), daemon=True
                ).start()
                threading.Thread(
                    target=_pipe_to_log, args=(proc.stderr, logging.WARNING), daemon=True
                ).start()
                log.info("serve.py started (pid=%d)", proc.pid)
            except Exception as exc:
                log.error("Failed to start serve.py: %s", exc)

    # ------------------------------------------------------------------ stop

    def stop(self, timeout: float = 5.0) -> None:
        with self._lock:
            proc = self._proc
            if proc is None or proc.poll() is not None:
                self._proc = None
                return
            log.info("Stopping serve.py (pid=%d, timeout=%.1fs)", proc.pid, timeout)
            try:
                proc.send_signal(signal.SIGTERM)
                deadline = time.monotonic() + timeout
                while time.monotonic() < deadline:
                    if proc.poll() is not None:
                        break
                    time.sleep(0.1)
                else:
                    log.warning("serve.py did not exit after SIGTERM; sending SIGKILL")
                    proc.kill()
                    proc.wait(timeout=3.0)
            except ProcessLookupError:
                pass  # process already gone
            except Exception as exc:
                log.error("Error stopping serve.py: %s", exc)
            finally:
                self._proc = None

    # --------------------------------------------------------------- restart

    def restart(self) -> None:
        self.stop()
        time.sleep(0.5)
        self.start()

    # --------------------------------------------------------------- is_alive

    @property
    def is_alive(self) -> bool:
        with self._lock:
            return self._proc is not None and self._proc.poll() is None


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------


def _check_health() -> bool:
    try:
        with urllib.request.urlopen(HEALTH_URL, timeout=2) as resp:
            return resp.status == 200
    except Exception:
        return False


# ---------------------------------------------------------------------------
# rumps App
# ---------------------------------------------------------------------------


class AdaMenuBar(rumps.App):  # type: ignore[misc]
    def __init__(self) -> None:
        icon = _find_icon()
        super().__init__(
            "Ada",
            title=STATUS_STARTING,
            icon=icon,
            template=False,  # keep the purple colour; template=True → greyscale
            quit_button=None,  # we provide our own Quit with clean shutdown
        )
        self._server = ServerManager()
        self._status = STATUS_STARTING

        self.menu = [
            rumps.MenuItem("Open Ada in browser", callback=self._open_browser),
            rumps.MenuItem("Show logs…", callback=self._show_logs),
            rumps.MenuItem("Restart server", callback=self._restart),
            None,  # separator
            rumps.MenuItem("Quit Ada", callback=self._quit),
        ]

        self._server.start()

    # ------------------------------------------------------------------ timer

    @rumps.timer(5)
    def _poll_health(self, _sender: object) -> None:
        if _check_health():
            new_status = STATUS_RUNNING
        elif self._server.is_alive:
            new_status = STATUS_STARTING
        else:
            # Server died unexpectedly — attempt automatic restart.
            new_status = STATUS_STOPPED
            log.warning("serve.py exited unexpectedly; attempting automatic restart")
            threading.Thread(target=self._server.start, daemon=True).start()

        if new_status != self._status:
            self._status = new_status
            self.title = new_status

    # --------------------------------------------------------------- callbacks

    def _open_browser(self, _sender: object) -> None:
        subprocess.run(["open", URL], check=False)

    def _show_logs(self, _sender: object) -> None:
        # Opens in Console.app or the user's default text editor.
        subprocess.run(["open", str(LOG_PATH)], check=False)

    def _restart(self, _sender: object) -> None:
        log.info("Restart requested via menu")
        self.title = STATUS_STARTING
        self._status = STATUS_STARTING
        threading.Thread(target=self._server.restart, daemon=True).start()

    def _quit(self, _sender: object) -> None:
        log.info("Quit requested via menu")
        self._server.stop(timeout=5.0)
        rumps.quit_application()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    log.info(
        "Ada menu-bar app starting — agent_dir=%s  venv_py=%s  log=%s",
        AGENT_DIR,
        VENV_PY,
        LOG_PATH,
    )
    AdaMenuBar().run()
