// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'primary' | 'mobile' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-V7DBXLRV.js";
import "../chunks/chunk-MJX6QVBH.js";
import "../chunks/chunk-NULYBL27.js";
import "../chunks/chunk-NFCCS2HW.js";
import { routes } from "../chunks/chunk-YOD5Q24P.js";

// virtual:cards/faq
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/exO8hjJJgrQHa748XQyS/irbZ9ARk2RlKDAhFpIO4/JZtpx7Nmg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ElementsFAQItemFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["Edtr6fzPB", "iFXIUtt7t"];
var serializationHash = "framer-5oO6Z";
var variantClassNames = {
	Edtr6fzPB: "framer-v-ln4err",
	iFXIUtt7t: "framer-v-18ixqlz",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition1 = {
	damping: 60,
	delay: 0.7,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	mobile: "iFXIUtt7t",
	primary: "Edtr6fzPB",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Edtr6fzPB",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Edtr6fzPB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-ln4err",
							className,
							classNames,
						)}
						data-framer-name={"primary"}
						layoutDependency={layoutDependency}
						layoutId={"Edtr6fzPB"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								iFXIUtt7t: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 390) - 0 - 304) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									iFXIUtt7t: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 312) - 0 - 304) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1hd0od1-container"}
								layoutDependency={layoutDependency}
								layoutId={"zdAQaCiXj-container"}
								nodeId={"zdAQaCiXj"}
								rendersWithMotion={true}
								scopeId={"JZtpx7Nmg"}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"We specialize in automating repetitive workflows across operations, marketing, sales, and customer support using AI and custom logic.",
									height: "100%",
									id: "zdAQaCiXj",
									layoutId: "zdAQaCiXj",
									pNqA5B2sU: "What types of processes can you automate?",
									style: {
										width: "100%",
									},
									variant: "QAvUnlGpo",
									width: "100%",
									...addPropertyOverrides(
										{
											iFXIUtt7t: {
												variant: "KlM6KShnm",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 390) - 0 - 304) / 2 + 48 + 16)
							}
							{...addPropertyOverrides(
								{
									iFXIUtt7t: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 312) - 0 - 304) / 2 +
												48 +
												16),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-uhd167-container"}
								layoutDependency={layoutDependency}
								layoutId={"crxJ1ydLD-container"}
								nodeId={"crxJ1ydLD"}
								rendersWithMotion={true}
								scopeId={"JZtpx7Nmg"}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"Not at all. Our team handles the setup, integration, and optimization. You just focus on your goals \u2014 we\u2019ll automate the rest.",
									height: "100%",
									id: "crxJ1ydLD",
									layoutId: "crxJ1ydLD",
									pNqA5B2sU:
										"Do I need technical knowledge to use your service?",
									style: {
										width: "100%",
									},
									variant: "SF38uWa4S",
									width: "100%",
									...addPropertyOverrides(
										{
											iFXIUtt7t: {
												variant: "KlM6KShnm",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 390) - 0 - 304) / 2 + 96 + 32)
							}
							{...addPropertyOverrides(
								{
									iFXIUtt7t: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 312) - 0 - 304) / 2 +
												96 +
												32),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-lmbi3c-container"}
								layoutDependency={layoutDependency}
								layoutId={"oWeDSST6C-container"}
								nodeId={"oWeDSST6C"}
								rendersWithMotion={true}
								scopeId={"JZtpx7Nmg"}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"Yes! We support integrations with CRMs, project management tools, communication apps, and more \u2014 tailored to your stack.",
									height: "100%",
									id: "oWeDSST6C",
									layoutId: "oWeDSST6C",
									pNqA5B2sU: "Can you integrate with our existing tools?",
									style: {
										width: "100%",
									},
									variant: "SF38uWa4S",
									width: "100%",
									...addPropertyOverrides(
										{
											iFXIUtt7t: {
												variant: "KlM6KShnm",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 390) - 0 - 304) / 2 + 144 + 48)
							}
							{...addPropertyOverrides(
								{
									iFXIUtt7t: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 312) - 0 - 304) / 2 +
												144 +
												48),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1hwchim-container"}
								layoutDependency={layoutDependency}
								layoutId={"io9j_bFtM-container"}
								nodeId={"io9j_bFtM"}
								rendersWithMotion={true}
								scopeId={"JZtpx7Nmg"}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"Most clients see their first automation live within 1\u20132 weeks, depending on complexity and the number of workflows.",
									height: "100%",
									id: "io9j_bFtM",
									layoutId: "io9j_bFtM",
									pNqA5B2sU: "How long does implementation take?",
									style: {
										width: "100%",
									},
									variant: "SF38uWa4S",
									width: "100%",
									...addPropertyOverrides(
										{
											iFXIUtt7t: {
												variant: "KlM6KShnm",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={48}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 390) - 0 - 304) / 2 + 192 + 64)
							}
							{...addPropertyOverrides(
								{
									iFXIUtt7t: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 312) - 0 - 304) / 2 +
												192 +
												64),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-11y11vx-container"}
								layoutDependency={layoutDependency}
								layoutId={"RMiXR9cAd-container"}
								nodeId={"RMiXR9cAd"}
								rendersWithMotion={true}
								scopeId={"JZtpx7Nmg"}
							>
								{_jsx(stdin_default, {
									aU1_lXl6h:
										"Absolutely. We use enterprise-grade security practices and ensure compliance with major data privacy standards like GDPR.",
									height: "100%",
									id: "RMiXR9cAd",
									layoutId: "RMiXR9cAd",
									pNqA5B2sU: "Is your AI secure and compliant?",
									style: {
										width: "100%",
									},
									variant: "SF38uWa4S",
									width: "100%",
									...addPropertyOverrides(
										{
											iFXIUtt7t: {
												variant: "KlM6KShnm",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5oO6Z.framer-1b0arvh, .framer-5oO6Z .framer-1b0arvh { display: block; }",
	".framer-5oO6Z.framer-ln4err { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 467px; }",
	".framer-5oO6Z .framer-1hd0od1-container, .framer-5oO6Z .framer-uhd167-container, .framer-5oO6Z .framer-lmbi3c-container, .framer-5oO6Z .framer-1hwchim-container, .framer-5oO6Z .framer-11y11vx-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerJZtpx7Nmg = withCSS(Component, css, "framer-5oO6Z");
var stdin_default2 = FramerJZtpx7Nmg;
FramerJZtpx7Nmg.displayName = "Cards/FAQ";
FramerJZtpx7Nmg.defaultProps = {
	height: 390,
	width: 467,
};
addPropertyControls(FramerJZtpx7Nmg, {
	variant: {
		options: ["Edtr6fzPB", "iFXIUtt7t"],
		optionTitles: ["primary", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerJZtpx7Nmg,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ElementsFAQItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cards/faq
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "iFXIUtt7t",
	xl: "Edtr6fzPB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_default = ComponentWithRoot;
export { faq_default as default };
