// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * hover?: Function // Hover
 * title?: string // Title
 * discription?: string // discription
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "../chunks/chunk-YLF6WDSY.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-D7GXE4AY.js";
import { className, css, fonts } from "../chunks/chunk-2X2OXJIF.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-NFCCS2HW.js";
import { routes } from "../chunks/chunk-YOD5Q24P.js";

// virtual:cards/feature-card-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/w5gyrNAldDfxwR3lnodE/n93SEzqsZI3PKe0UEBY0/yfYFZNV6I.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SVG as SVG2,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/tjjgb98omlVa09zHARR4/ggRLlXNJnxV689eAMtLP/LLhYBfdqv.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 5.625 C 0 2.518 2.518 0 5.625 0 C 8.732 0 11.25 2.518 11.25 5.625 C 11.25 8.732 8.732 11.25 5.625 11.25 C 2.518 11.25 0 8.732 0 5.625 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="11.25px" id="FvOEQsPdS" transform="translate(4.5 3.75)" width="11.25px"/><path d="M 0 5.625 C 0 2.518 2.518 0 5.625 0 C 8.732 0 11.25 2.518 11.25 5.625 C 11.25 8.732 8.732 11.25 5.625 11.25 C 2.518 11.25 0 8.732 0 5.625 Z" fill="transparent" height="11.25px" id="WAzt5bQVL" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(4.5 3.75)" width="11.25px"/><path d="M 0 3.75 C 1.927 1.458 4.646 0 7.875 0 C 11.104 0 13.823 1.458 15.75 3.75" fill="transparent" height="3.75px" id="aF2lKQXzJ" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(2.25 15)" width="15.75px"/><path d="M 0 1.5 L 1.5 3 L 4.5 0" fill="transparent" height="3px" id="K9gYvV6pW" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(18.75 12)" width="4.5px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className5,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("3752660003", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-jGjLl", className5)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css5 = [
	`.framer-jGjLl { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css5, "framer-jGjLl");
Icon.displayName = "User Check";
var stdin_default = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/w5gyrNAldDfxwR3lnodE/n93SEzqsZI3PKe0UEBY0/yfYFZNV6I.js
var UserCheckFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var serializationHash = "framer-ieUXb";
var variantClassNames = {
	sXidLTGSs: "framer-v-1ae5fc7",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 80,
};
var transition2 = {
	delay: 0.2,
	duration: 1,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({
	discription,
	height,
	hover,
	id,
	title,
	width,
	...props
}) => {
	return {
		...props,
		LEnKfYtg5: title ?? props.LEnKfYtg5 ?? "Real-Time Intelligence",
		uvJH3t4DP: hover ?? props.uvJH3t4DP,
		xEl67eLKG:
			discription ??
			props.xEl67eLKG ??
			"Access accurate, real-time data to drive smarter decisions",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		uvJH3t4DP,
		LEnKfYtg5,
		xEl67eLKG,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "sXidLTGSs",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterw3dggo = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (uvJH3t4DP) {
			const res = await uvJH3t4DP(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className3, className4, className, className2];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1ae5fc7",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"sXidLTGSs"}
						onMouseEnter={onMouseEnterw3dggo}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						<MotionDivWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0.5}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-156t5gd"}
							data-framer-name={"graphic 2"}
							layoutDependency={layoutDependency}
							layoutId={"AiYIbXqAU"}
							style={{
								scale: 0.7,
							}}
						>
							<motion2.div
								className={"framer-10bk3cf"}
								data-framer-name={"graphic container"}
								layoutDependency={layoutDependency}
								layoutId={"FnCJ2t0qx"}
							>
								<motion2.div
									className={"framer-1mydaiq"}
									data-border={true}
									data-framer-name={"screen"}
									layoutDependency={layoutDependency}
									layoutId={"LCSvqZ7Ih"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										background:
											"linear-gradient(180deg, var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28)) 0%, rgb(0, 0, 0) 27%)",
										borderBottomLeftRadius: 13,
										borderBottomRightRadius: 13,
										borderTopLeftRadius: 13,
										borderTopRightRadius: 13,
										boxShadow:
											"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.15)",
									}}
								>
									<motion2.div
										className={"framer-1grm79"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"mnqZ6yMp7"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backdropFilter: "blur(8px)",
											backgroundColor:
												"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
											borderBottomLeftRadius: 32,
											borderBottomRightRadius: 32,
											borderTopLeftRadius: 32,
											borderTopRightRadius: 32,
											boxShadow:
												"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.15)",
											WebkitBackdropFilter: "blur(8px)",
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-vwvawj"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"JjDZaCFPP"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-17f5k4v"}
													data-styles-preset={"rmSf_ipOK"}
												>
													{"Research anything..."}
												</motion2.p>
											</React2.Fragment>
										</RichText>
										<motion2.div
											className={"framer-3pftwf"}
											layoutDependency={layoutDependency}
											layoutId={"xdzJ9wYa_"}
											style={{
												backgroundColor: "rgb(94, 94, 94)",
											}}
										/>
										<motion2.div
											className={"framer-5tt3i2"}
											data-framer-name={"Group 5"}
											layoutDependency={layoutDependency}
											layoutId={"pesKgkMlo"}
											style={{
												background:
													"linear-gradient(175deg, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)) 0%, var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)) 100%)",
												borderBottomLeftRadius: 30,
												borderBottomRightRadius: 30,
												borderTopLeftRadius: 30,
												borderTopRightRadius: 30,
											}}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1ievf3s"}
												data-framer-name={"Generate Idea"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"bFTi1rucz"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														style={{
															"--framer-font-size": "14px",
															"--framer-text-alignment": "center",
														}}
													>
														{"Research"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
										</motion2.div>
									</motion2.div>
									<motion2.div
										className={"framer-1vucll8"}
										layoutDependency={layoutDependency}
										layoutId={"ztVFJslfO"}
									>
										<motion2.div
											className={"framer-1kpki48"}
											data-border={true}
											data-framer-name={"Rectangle 4"}
											layoutDependency={layoutDependency}
											layoutId={"Rwcibjj3C"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
												borderBottomLeftRadius: 6,
												borderBottomRightRadius: 6,
												borderTopLeftRadius: 6,
												borderTopRightRadius: 6,
												boxShadow:
													"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.15)",
											}}
											transformTemplate={transformTemplate1}
										>
											{_jsx2(stdin_default, {
												animated: true,
												className: "framer-pu52f7",
												layoutDependency,
												layoutId: "WdpxWoiAT",
												style: {
													"--1m6trwb": 0.2,
													"--21h8s6": "rgb(255, 255, 255)",
													"--pgex8v": 1.5,
												},
											})}
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1ort0hw"}
												data-framer-name={"Web Services Business"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"SXlx0rMU7"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-1u349i7"}
														data-styles-preset={"rerWrmQ65"}
													>
														{"Software & App Industry"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<SVG2
												className={"framer-10qjnpe"}
												data-framer-name={
													"streamline:money-graph-arrow-increase-ascend-growth-up-arrow-stats-graph-right-grow"
												}
												layout={"position"}
												layoutDependency={layoutDependency}
												layoutId={"jx6Vh2_HC"}
												opacity={1}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 18"><path d="M 12.214 4.5 L 17.357 4.5 L 17.357 9.643" fill="transparent" stroke="rgb(194, 194, 194)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 17.357 4.5 L 10.093 11.764 C 9.973 11.882 9.811 11.948 9.643 11.948 C 9.475 11.948 9.313 11.882 9.193 11.764 L 6.236 8.807 C 6.116 8.689 5.954 8.623 5.786 8.623 C 5.618 8.623 5.456 8.689 5.336 8.807 L 0.643 13.5" fill="transparent" stroke="rgb(194, 194, 194)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
												}
												svgContentId={11902110705}
												withExternalLayout={true}
											/>
										</motion2.div>
										<motion2.div
											className={"framer-1ekun4d"}
											data-border={true}
											data-framer-name={"Rectangle 4"}
											layoutDependency={layoutDependency}
											layoutId={"AB5MDbxok"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
												borderBottomLeftRadius: 6,
												borderBottomRightRadius: 6,
												borderTopLeftRadius: 6,
												borderTopRightRadius: 6,
												boxShadow:
													"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.15)",
											}}
										>
											{_jsx2(stdin_default, {
												animated: true,
												className: "framer-1inbxur",
												layoutDependency,
												layoutId: "tWqwb8PFd",
												style: {
													"--1m6trwb": 0.2,
													"--21h8s6": "rgb(255, 255, 255)",
													"--pgex8v": 1.5,
												},
											})}
											<RichText
												__fromCanvasComponent={true}
												className={"framer-mmf3fq"}
												data-framer-name={"Web Services Business"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"fFlicL8ci"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-1u349i7"}
														data-styles-preset={"rerWrmQ65"}
													>
														{"UX & UI Design Industry"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<SVG2
												className={"framer-pk23w"}
												data-framer-name={
													"streamline:money-graph-arrow-increase-ascend-growth-up-arrow-stats-graph-right-grow"
												}
												layout={"position"}
												layoutDependency={layoutDependency}
												layoutId={"wdQpSKri_"}
												opacity={1}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 18"><path d="M 12.214 4.5 L 17.357 4.5 L 17.357 9.643" fill="transparent" stroke="rgb(194, 194, 194)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 17.357 4.5 L 10.093 11.764 C 9.973 11.882 9.811 11.948 9.643 11.948 C 9.475 11.948 9.313 11.882 9.193 11.764 L 6.236 8.807 C 6.116 8.689 5.954 8.623 5.786 8.623 C 5.618 8.623 5.456 8.689 5.336 8.807 L 0.643 13.5" fill="transparent" stroke="rgb(194, 194, 194)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
												}
												svgContentId={11902110705}
												withExternalLayout={true}
											/>
										</motion2.div>
										<motion2.div
											className={"framer-ftg0vm"}
											data-border={true}
											data-framer-name={"Rectangle 4"}
											layoutDependency={layoutDependency}
											layoutId={"v7KT6u4tM"}
											style={{
												"--border-bottom-width": "1px",
												"--border-color":
													"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
												"--border-left-width": "1px",
												"--border-right-width": "1px",
												"--border-style": "solid",
												"--border-top-width": "1px",
												backgroundColor:
													"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
												borderBottomLeftRadius: 6,
												borderBottomRightRadius: 6,
												borderTopLeftRadius: 6,
												borderTopRightRadius: 6,
												boxShadow:
													"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.15)",
											}}
											transformTemplate={transformTemplate1}
										>
											{_jsx2(stdin_default, {
												animated: true,
												className: "framer-1thzarh",
												layoutDependency,
												layoutId: "IVI4SEuhb",
												style: {
													"--1m6trwb": 0.2,
													"--21h8s6": "rgb(255, 255, 255)",
													"--pgex8v": 1.5,
												},
											})}
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1h5nasa"}
												data-framer-name={"Web Services Business"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"wVgcGzxzQ"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-1u349i7"}
														data-styles-preset={"rerWrmQ65"}
													>
														{"High Converting Customer"}
													</motion2.p>
												</React2.Fragment>
											</RichText>
											<SVG2
												className={"framer-o0tjwu"}
												data-framer-name={
													"streamline:money-graph-arrow-increase-ascend-growth-up-arrow-stats-graph-right-grow"
												}
												layout={"position"}
												layoutDependency={layoutDependency}
												layoutId={"pZ7Gj3J32"}
												opacity={1}
												svg={
													'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 18"><path d="M 12.214 4.5 L 17.357 4.5 L 17.357 9.643" fill="transparent" stroke="rgb(194, 194, 194)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 17.357 4.5 L 10.093 11.764 C 9.973 11.882 9.811 11.948 9.643 11.948 C 9.475 11.948 9.313 11.882 9.193 11.764 L 6.236 8.807 C 6.116 8.689 5.954 8.623 5.786 8.623 C 5.618 8.623 5.456 8.689 5.336 8.807 L 0.643 13.5" fill="transparent" stroke="rgb(194, 194, 194)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
												}
												svgContentId={11902110705}
												withExternalLayout={true}
											/>
										</motion2.div>
									</motion2.div>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-unymcu"}
								layoutDependency={layoutDependency}
								layoutId={"sibMnq93D"}
								style={{
									backgroundColor:
										"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.15)",
									filter: "blur(1px)",
									WebkitFilter: "blur(1px)",
								}}
							/>
							<motion2.div
								className={"framer-htrm55"}
								layoutDependency={layoutDependency}
								layoutId={"zKzMmqufO"}
								style={{
									backgroundColor: "rgb(13, 15, 23)",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.15)",
								}}
							/>
							<motion2.div
								className={"framer-ycqzc8"}
								layoutDependency={layoutDependency}
								layoutId={"RhseRZYdX"}
								style={{
									backgroundColor: "rgb(20, 20, 20)",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									boxShadow:
										"0px -0.7961918735236395px 0.7961918735236395px -0.9375px rgba(0, 0, 0, 0.15), 0px -2.414506143104518px 2.414506143104518px -1.875px rgba(0, 0, 0, 0.14), 0px -6.382653521484461px 6.382653521484461px -2.8125px rgba(0, 0, 0, 0.12), 0px -20px 20px -3.75px rgba(0, 0, 0, 0.05)",
								}}
							/>
						</MotionDivWithFX>
						<motion2.div
							className={"framer-6cl6dt"}
							data-framer-name={"Text Container"}
							layoutDependency={layoutDependency}
							layoutId={"hgcanJn_W"}
						>
							<motion2.div
								className={"framer-1yd8356"}
								data-framer-name={"overlay"}
								layoutDependency={layoutDependency}
								layoutId={"XWXUR_E4U"}
								style={{
									background:
										"linear-gradient(180deg, rgba(4, 7, 13, 0) 0%, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13)) 60.00000000000001%)",
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1j22s8f"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Ee1peg7cB"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={LEnKfYtg5}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-i6z8by"}
										data-styles-preset={"j3hccNIu_"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"Real-Time Intelligence"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1xq6udd"}
								data-framer-name={"Paragraph"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ZfNTNwJEm"}
								style={{
									"--framer-paragraph-spacing": "0px",
									opacity: 0.6,
								}}
								text={xEl67eLKG}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{
											"Access accurate, real-time data to drive smarter decisions"
										}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.div>
						<motion2.div
							className={"framer-1dpmp1d"}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"tuKYLe6mF"}
							style={{
								background:
									"radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) 0%, rgba(4, 7, 13, 0) 100%)",
								opacity: 0.1,
							}}
						/>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ieUXb.framer-1srj5w, .framer-ieUXb .framer-1srj5w { display: block; }",
	".framer-ieUXb.framer-1ae5fc7 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 396px; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 414px; will-change: var(--framer-will-change-override, transform); }",
	".framer-ieUXb .framer-156t5gd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: -21px; overflow: visible; padding: 0px; position: absolute; right: -19px; top: -12px; z-index: 1; }",
	".framer-ieUXb .framer-10bk3cf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-ieUXb .framer-1mydaiq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; padding: 40px 30px 0px 30px; position: relative; width: 100%; z-index: 1; }",
	".framer-ieUXb .framer-1grm79 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 24px 10px 24px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 6; }",
	".framer-ieUXb .framer-vwvawj { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 6; }",
	".framer-ieUXb .framer-3pftwf { flex: none; height: 35px; overflow: hidden; position: relative; width: 1px; }",
	".framer-ieUXb .framer-5tt3i2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; max-width: 150px; overflow: visible; padding: 8px 24px 8px 24px; position: relative; width: min-content; }",
	".framer-ieUXb .framer-1ievf3s { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ieUXb .framer-1vucll8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: wrap; gap: 10px; height: 211px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-ieUXb .framer-1kpki48 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; left: 50%; padding: 10px 14px 10px 14px; position: absolute; top: 0px; width: 334px; z-index: 1; }",
	".framer-ieUXb .framer-pu52f7, .framer-ieUXb .framer-1inbxur, .framer-ieUXb .framer-1thzarh { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-ieUXb .framer-1ort0hw, .framer-ieUXb .framer-mmf3fq, .framer-ieUXb .framer-1h5nasa { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-ieUXb .framer-10qjnpe, .framer-ieUXb .framer-pk23w, .framer-ieUXb .framer-o0tjwu { flex: none; height: 18px; position: relative; width: 18px; }",
	".framer-ieUXb .framer-1ekun4d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; padding: 10px 14px 10px 14px; position: absolute; right: -10px; top: 64px; width: 334px; z-index: 1; }",
	".framer-ieUXb .framer-ftg0vm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; left: 50%; padding: 10px 14px 10px 14px; position: absolute; top: 127px; width: 334px; z-index: 1; }",
	".framer-ieUXb .framer-unymcu { flex: none; gap: 20px; height: 163px; left: calc(50.10482180293503% - 84.69601677148847% / 2); overflow: hidden; position: absolute; top: -15px; width: 85%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-ieUXb .framer-htrm55 { flex: none; gap: 20px; height: 154px; left: calc(50.10482180293503% - 88.67924528301887% / 2); overflow: hidden; position: absolute; top: -7px; width: 89%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-ieUXb .framer-ycqzc8 { flex: none; gap: 20px; height: 150px; left: calc(50.10482180293503% - 93.50104821802935% / 2); overflow: hidden; position: absolute; top: 0px; width: 94%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-ieUXb .framer-6cl6dt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 30px; position: relative; width: 100%; z-index: 1; }",
	".framer-ieUXb .framer-1yd8356 { bottom: 2px; flex: none; left: 2px; overflow: visible; position: absolute; right: 2px; top: -96px; z-index: 1; }",
	".framer-ieUXb .framer-1j22s8f, .framer-ieUXb .framer-1xq6udd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-ieUXb .framer-1dpmp1d { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	...css3,
	...css4,
	...css,
	...css2,
	'.framer-ieUXb[data-border="true"]::after, .framer-ieUXb [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameryfYFZNV6I = withCSS2(Component2, css6, "framer-ieUXb");
var stdin_default2 = FrameryfYFZNV6I;
FrameryfYFZNV6I.displayName = "Cards/Feature Card 2";
FrameryfYFZNV6I.defaultProps = {
	height: 396,
	width: 414,
};
addPropertyControls2(FrameryfYFZNV6I, {
	uvJH3t4DP: {
		title: "Hover",
		type: ControlType2.EventHandler,
	},
	LEnKfYtg5: {
		defaultValue: "Real-Time Intelligence",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	xEl67eLKG: {
		defaultValue: "Access accurate, real-time data to drive smarter decisions",
		displayTextArea: true,
		title: "discription",
		type: ControlType2.String,
	},
});
addFonts(
	FrameryfYFZNV6I,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...UserCheckFonts,
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cards/feature-card-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tiCGwxfhf",
	xl: "NlXlWXy00",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeatureCard2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var feature_card_2_default = ComponentWithRoot;
export { feature_card_2_default as default };
