// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' // Variant
 * icon1?: any // Icon 1
 * icon2?: any // Icon 2
 * title?: string // Title
 * description?: string // Description
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-2X2OXJIF.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:benefit-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7nRr3rQKdKIKPjfPn3nQ/T64L0duceRpSh11l1qSt/p1BSlpAY1.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/TSJnBHCoTudd7jV0m8ho/nOegbf0BK65ohKUrXcj3/ypPlcIn1s.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-so0dz", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css3 = [
	`.framer-so0dz { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="House" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 17.56 7.939 L 10.06 0.439 C 9.475 -0.146 8.525 -0.146 7.94 0.439 L 0.44 7.939 C 0.157 8.22 -0.001 8.602 0 9 L 0 18 C 0 18.414 0.336 18.75 0.75 18.75 L 6.75 18.75 C 7.164 18.75 7.5 18.414 7.5 18 L 7.5 12.75 L 10.5 12.75 L 10.5 18 C 10.5 18.414 10.836 18.75 11.25 18.75 L 17.25 18.75 C 17.664 18.75 18 18.414 18 18 L 18 9 C 18.001 8.602 17.843 8.22 17.56 7.939 Z M 16.5 17.25 L 12 17.25 L 12 12 C 12 11.586 11.664 11.25 11.25 11.25 L 6.75 11.25 C 6.336 11.25 6 11.586 6 12 L 6 17.25 L 1.5 17.25 L 1.5 9 L 9 1.5 L 16.5 9 Z" fill="var(--21h8s6, rgb(0,0,0))" height="18.75024227036556px" id="FjiNvMtHp" opacity="1" transform="translate(3 2.25)" width="18.0000188761428px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-so0dz");
var stdin_default = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/7nRr3rQKdKIKPjfPn3nQ/T64L0duceRpSh11l1qSt/p1BSlpAY1.js
var MotionDivWithFX = withFX(motion2.div);
var enabledGestures = {
	ioJ9WwnlF: {
		hover: true,
	},
};
var cycleOrder = ["ioJ9WwnlF", "VyB8MLUSd"];
var serializationHash = "framer-fffKU";
var variantClassNames = {
	ioJ9WwnlF: "framer-v-1p8b3ay",
	VyB8MLUSd: "framer-v-gqy2vs",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var inertia = {
	bounceDamping: 30,
	bounceStiffness: 385,
	delay: 0,
	type: "inertia",
};
var preventDefault = (e) => e.preventDefault();
var animation = {
	cursor: "grabbing",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	desktop: "ioJ9WwnlF",
	mobile: "VyB8MLUSd",
};
var getProps2 = ({
	description,
	height,
	icon1,
	icon2,
	id,
	title,
	width,
	...props
}) => {
	return {
		...props,
		jlPwWcQIY: description ?? props.jlPwWcQIY ?? "Description",
		tXEKlN7zT: title ?? props.tXEKlN7zT ?? "Title",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ioJ9WwnlF",
		vK3kOQCVU: icon1 ?? props.vK3kOQCVU ?? stdin_default,
		wOz6SIE9p: icon2 ?? props.wOz6SIE9p ?? stdin_default,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		vK3kOQCVU,
		wOz6SIE9p,
		tXEKlN7zT,
		jlPwWcQIY,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ioJ9WwnlF",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1p8b3ay",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"desktop"}
						layoutDependency={layoutDependency}
						layoutId={"ioJ9WwnlF"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"ioJ9WwnlF-hover": {
									"data-framer-name": void 0,
								},
								VyB8MLUSd: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-13hhohp"}
							data-framer-name={"icon container"}
							layoutDependency={layoutDependency}
							layoutId={"FCCheN2OX"}
							style={{
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
							}}
						>
							<MotionDivWithFX
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-n0oaej"}
								data-framer-name={"Icon container"}
								drag={true}
								dragMomentum={false}
								dragSnapToOrigin={true}
								dragTransition={inertia}
								layoutDependency={layoutDependency}
								layoutId={"w18mQq6Un"}
								onMouseDown={preventDefault}
								style={{
									backgroundColor:
										"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
									scale: 1,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									"ioJ9WwnlF-hover": {
										scale: 1.1,
									},
								}}
								whileTap={animation}
								{...addPropertyOverrides(
									{
										VyB8MLUSd: {
											drag: void 0,
											onMouseDown: void 0,
											whileTap: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<Instance
									animated={true}
									className={"framer-vgqtn2"}
									Component={vK3kOQCVU}
									layoutDependency={layoutDependency}
									layoutId={"KW62lxSYy"}
									style={{
										"--21h8s6":
											"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
										opacity: 0.5,
									}}
									variants={{
										"ioJ9WwnlF-hover": {
											opacity: 1,
										},
										VyB8MLUSd: {
											opacity: 1,
										},
									}}
								/>
								<motion2.div
									className={"framer-35mfbi"}
									data-framer-name={"line"}
									layoutDependency={layoutDependency}
									layoutId={"oe0NvlPsQ"}
									style={{
										backgroundColor:
											"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
									}}
								/>
								<Instance
									animated={true}
									className={"framer-aoageo"}
									Component={wOz6SIE9p}
									layoutDependency={layoutDependency}
									layoutId={"wz4Pt_7qb"}
									style={{
										"--21h8s6":
											"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
										opacity: 0.5,
									}}
									variants={{
										"ioJ9WwnlF-hover": {
											opacity: 1,
										},
										VyB8MLUSd: {
											opacity: 1,
										},
									}}
								/>
							</MotionDivWithFX>
							<motion2.div
								className={"framer-1whf08r"}
								data-framer-name={"Light"}
								layoutDependency={layoutDependency}
								layoutId={"uVMqB9ab1"}
								style={{
									background:
										"radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) 0%, rgba(4, 7, 13, 0) 100%)",
									opacity: 0.1,
								}}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-sll7a2"}
							data-framer-name={"Text container"}
							layoutDependency={layoutDependency}
							layoutId={"T6O6vV5Qh"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1ba8xj2"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"UkbfRlmKz"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={tXEKlN7zT}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-i6z8by"}
										data-styles-preset={"j3hccNIu_"}
									>
										{"Title"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ez90ap"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"QTsJjLwld"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 0.6,
								}}
								text={jlPwWcQIY}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
										style={{
											"--framer-text-alignment": "center",
										}}
									>
										{"Description"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.div>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-fffKU.framer-lbgx25, .framer-fffKU .framer-lbgx25 { display: block; }",
	".framer-fffKU.framer-1p8b3ay { align-content: center; align-items: center; cursor: default; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 25px; height: min-content; justify-content: center; overflow: visible; padding: 32px; position: relative; width: 350px; }",
	".framer-fffKU .framer-13hhohp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: 160px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-fffKU .framer-n0oaej { align-content: center; align-items: center; cursor: grab; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 12px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
	".framer-fffKU .framer-vgqtn2, .framer-fffKU .framer-aoageo { flex: none; height: var(--framer-aspect-ratio-supported, 40px); position: relative; width: 40px; }",
	".framer-fffKU .framer-35mfbi { flex: none; height: 38px; overflow: visible; position: relative; width: 1px; }",
	".framer-fffKU .framer-1whf08r { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	".framer-fffKU .framer-sll7a2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-fffKU .framer-1ba8xj2, .framer-fffKU .framer-ez90ap { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-fffKU.framer-v-gqy2vs .framer-n0oaej { cursor: unset; }",
	".framer-fffKU.framer-v-1p8b3ay.hover .framer-vgqtn2 { order: 0; }",
	".framer-fffKU.framer-v-1p8b3ay.hover .framer-35mfbi { order: 1; }",
	".framer-fffKU.framer-v-1p8b3ay.hover .framer-aoageo { order: 2; }",
	...css,
	...css2,
	'.framer-fffKU[data-border="true"]::after, .framer-fffKU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerp1BSlpAY1 = withCSS2(Component2, css4, "framer-fffKU");
var stdin_default2 = Framerp1BSlpAY1;
Framerp1BSlpAY1.displayName = "Benefit card";
Framerp1BSlpAY1.defaultProps = {
	height: 309,
	width: 350,
};
addPropertyControls2(Framerp1BSlpAY1, {
	variant: {
		options: ["ioJ9WwnlF", "VyB8MLUSd"],
		optionTitles: ["desktop", "mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	vK3kOQCVU: {
		defaultValue: {
			identifier:
				"module:TSJnBHCoTudd7jV0m8ho/nOegbf0BK65ohKUrXcj3/ypPlcIn1s.js:default",
			moduleId: "TSJnBHCoTudd7jV0m8ho",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon 1",
		type: ControlType2.VectorSetItem,
	},
	wOz6SIE9p: {
		defaultValue: {
			identifier:
				"module:TSJnBHCoTudd7jV0m8ho/nOegbf0BK65ohKUrXcj3/ypPlcIn1s.js:default",
			moduleId: "TSJnBHCoTudd7jV0m8ho",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon 2",
		type: ControlType2.VectorSetItem,
	},
	tXEKlN7zT: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	jlPwWcQIY: {
		defaultValue: "Description",
		displayTextArea: true,
		title: "Description",
		type: ControlType2.String,
	},
});
addFonts(
	Framerp1BSlpAY1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:benefit-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VyB8MLUSd",
	xl: "ioJ9WwnlF",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BenefitCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var benefit_card_default = ComponentWithRoot;
export { benefit_card_default as default };
