// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * icon?: any // Icon
 * title?: string // Title
 * description?: string // Description
 * linkText?: string // Link text
 * link?: string // Link
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-MDFUVCZL.js";
import { className, css, fonts } from "./chunks/chunk-2X2OXJIF.js";
import { stdin_default } from "./chunks/chunk-GD2KCKTC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:contact-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fCDSuVUGvWTbwfyXTcOh/bk9lTbX7MuJePLcsMedP/Ix5MkWr4G.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Instance,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-Mn743";
var variantClassNames = {
	taXL_KV39: "framer-v-1fgjmzn",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	description,
	height,
	icon,
	id,
	link,
	linkText,
	title,
	width,
	...props
}) => {
	return {
		...props,
		j99nipSOu: title ?? props.j99nipSOu ?? "Email Us",
		mMVNKlGDF:
			description ??
			props.mMVNKlGDF ??
			"Facing technical challenges or product concerns? We\u2019re here to assist",
		rP8Jq5Q0s: link ?? props.rP8Jq5Q0s,
		su6aooHab: icon ?? props.su6aooHab ?? stdin_default,
		TLJ29SMlg: linkText ?? props.TLJ29SMlg ?? "landio@support.com",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		su6aooHab,
		j99nipSOu,
		mMVNKlGDF,
		TLJ29SMlg,
		rP8Jq5Q0s,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "taXL_KV39",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1fgjmzn",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"taXL_KV39"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						<motion.div
							className={"framer-v08jij"}
							data-framer-name={"content"}
							layoutDependency={layoutDependency}
							layoutId={"r6_pwxJjt"}
						>
							<motion.div
								className={"framer-d2iq9r"}
								data-framer-name={"icon&text"}
								layoutDependency={layoutDependency}
								layoutId={"N2uUPNu3G"}
							>
								<motion.div
									className={"framer-pyil30"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"DLxD90peo"}
									style={{
										backgroundColor:
											"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
										boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
									}}
								>
									<Instance
										animated={true}
										className={"framer-iatkhl"}
										Component={su6aooHab}
										layoutDependency={layoutDependency}
										layoutId={"JpALiujZR"}
										style={{
											"--21h8s6":
												"var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255))",
										}}
									/>
								</motion.div>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-s5olnb"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"TiSXbgG6w"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={j99nipSOu}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-i6z8by"}
											data-styles-preset={"j3hccNIu_"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"Email Us"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-efy1m9"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"GLjONy750"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 0.8,
								}}
								text={mMVNKlGDF}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
									>
										{
											"Facing technical challenges or product concerns? We\u2019re here to assist"
										}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-gy4wwr"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"TUvYnIxre"}
								text={TLJ29SMlg}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
									>
										<Link
											href={rP8Jq5Q0s}
											motionChild={true}
											nodeId={"TUvYnIxre"}
											openInNewTab={true}
											relValues={[]}
											scopeId={"Ix5MkWr4G"}
											smoothScroll={false}
										>
											<motion.a
												className={"framer-styles-preset-z4q089"}
												data-styles-preset={"o77HbpIl9"}
											>
												{"alter@support.com"}
											</motion.a>
										</Link>
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-1m3de6s"}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"qcnYaJIms"}
							style={{
								background:
									"radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) 0%, rgba(4, 7, 13, 0) 100%)",
								opacity: 0.1,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Mn743.framer-10pl2iy, .framer-Mn743 .framer-10pl2iy { display: block; }",
	".framer-Mn743.framer-1fgjmzn { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 32px; position: relative; width: 452px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Mn743 .framer-v08jij { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-Mn743 .framer-d2iq9r { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-Mn743 .framer-pyil30 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 12px; position: relative; width: min-content; }",
	".framer-Mn743 .framer-iatkhl { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 32px; }",
	".framer-Mn743 .framer-s5olnb { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-Mn743 .framer-efy1m9, .framer-Mn743 .framer-gy4wwr { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-Mn743 .framer-1m3de6s { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	...css,
	...css2,
	...css3,
	'.framer-Mn743[data-border="true"]::after, .framer-Mn743 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerIx5MkWr4G = withCSS(Component, css4, "framer-Mn743");
var stdin_default2 = FramerIx5MkWr4G;
FramerIx5MkWr4G.displayName = "contact card";
FramerIx5MkWr4G.defaultProps = {
	height: 229,
	width: 452,
};
addPropertyControls(FramerIx5MkWr4G, {
	su6aooHab: {
		defaultValue: {
			identifier:
				"module:QGsiOmymnPflDqXQHBDF/7ieEdtPrCagk41eLw1dF/VWXKKteE7.js:default",
			moduleId: "QGsiOmymnPflDqXQHBDF",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
	j99nipSOu: {
		defaultValue: "Email Us",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	mMVNKlGDF: {
		defaultValue:
			"Facing technical challenges or product concerns? We\u2019re here to assist",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	TLJ29SMlg: {
		defaultValue: "landio@support.com",
		displayTextArea: false,
		title: "Link text",
		type: ControlType.String,
	},
	rP8Jq5Q0s: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerIx5MkWr4G,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:contact-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var contact_card_default = ComponentWithRoot;
export { contact_card_default as default };
