// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * icon?: any // Icon
}} Props

 */
import { stdin_default } from "./chunks/chunk-GD2KCKTC.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:icon-card-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/20aWq354UtFKw6quGLRw/GMMgQsCgqEQJ9HcUDv8q/mp4fHASFw.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Instance,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-6JzKT";
var variantClassNames = {
	Iis0y6hUg: "framer-v-14kdk9r",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, icon, id, width, ...props }) => {
	return {
		...props,
		NtGaM9Q7r: icon ?? props.NtGaM9Q7r ?? stdin_default,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, NtGaM9Q7r, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Iis0y6hUg",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14kdk9r",
							className,
							classNames,
						)}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"Iis0y6hUg"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						<Instance
							animated={true}
							className={"framer-1jt1ao5"}
							Component={NtGaM9Q7r}
							layoutDependency={layoutDependency}
							layoutId={"u5xCQhBqh"}
							style={{
								"--21h8s6":
									"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6JzKT.framer-1y7ch2m, .framer-6JzKT .framer-1y7ch2m { display: block; }",
	".framer-6JzKT.framer-14kdk9r { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: 52px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 54px; }",
	".framer-6JzKT .framer-1jt1ao5 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 32px; }",
];
var Framermp4fHASFw = withCSS(Component, css, "framer-6JzKT");
var stdin_default2 = Framermp4fHASFw;
Framermp4fHASFw.displayName = "Icon card 2";
Framermp4fHASFw.defaultProps = {
	height: 52,
	width: 54,
};
addPropertyControls(Framermp4fHASFw, {
	NtGaM9Q7r: {
		defaultValue: {
			identifier:
				"module:QGsiOmymnPflDqXQHBDF/7ieEdtPrCagk41eLw1dF/VWXKKteE7.js:default",
			moduleId: "QGsiOmymnPflDqXQHBDF",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	Framermp4fHASFw,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:icon-card-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IconCard2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var icon_card_2_default = ComponentWithRoot;
export { icon_card_2_default as default };
