// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * logo?: {src: string, srcSet?: string, alt?: string} // logo
}} Props

 */
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:logo
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6aHX7lLv50tqI9kjHz66/2myRn8jjPoC5CiqLMT0i/KuUrcl5x_.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-s9Ols";
var variantClassNames = {
	wU9JPioIr: "framer-v-169g3he",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, logo, width, ...props }) => {
	return {
		...props,
		SYWdo3uYr: logo ??
			props.SYWdo3uYr ?? {
				alt: "",
				pixelHeight: 62,
				pixelWidth: 163,
				src: "https://framerusercontent.com/images/04vJJZ3D2ponPv6rzLBq6sf2PZU.svg",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, SYWdo3uYr, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "wU9JPioIr",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={{
							hash: ":E5xbXrjqj",
							webPageId: "augiA20Il",
						}}
						motionChild={true}
						nodeId={"wU9JPioIr"}
						openInNewTab={false}
						scopeId={"KuUrcl5x_"}
						smoothScroll={true}
					>
						<Image
							{...restProps}
							{...gestureHandlers}
							as={"a"}
							background={{
								alt: "",
								fit: "fit",
								loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
								pixelHeight: 62,
								pixelWidth: 163,
								sizes: componentViewport?.width || "100vw",
								...toResponsiveImage(SYWdo3uYr),
								...{
									positionX: "center",
									positionY: "center",
								},
							}}
							className={`${cx(scopingClassNames, "framer-169g3he", className, classNames)} framer-11n6r7`}
							data-framer-name={"primary"}
							layoutDependency={layoutDependency}
							layoutId={"wU9JPioIr"}
							ref={refBinding}
							style={{
								...style,
							}}
						/>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-s9Ols.framer-11n6r7, .framer-s9Ols .framer-11n6r7 { display: block; }",
	".framer-s9Ols.framer-169g3he { height: 39px; overflow: visible; position: relative; text-decoration: none; width: 103px; }",
];
var FramerKuUrcl5x_ = withCSS(Component, css, "framer-s9Ols");
var stdin_default = FramerKuUrcl5x_;
FramerKuUrcl5x_.displayName = "logo";
FramerKuUrcl5x_.defaultProps = {
	height: 39,
	width: 103,
};
addPropertyControls(FramerKuUrcl5x_, {
	SYWdo3uYr: {
		__defaultAssetReference:
			"data:framer/asset-reference,04vJJZ3D2ponPv6rzLBq6sf2PZU.svg?originalFilename=Group+80ghgfd86.svg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,04vJJZ3D2ponPv6rzLBq6sf2PZU.svg?originalFilename=Group+80ghgfd86.svg&preferredSize=auto",
		},
		title: "logo",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerKuUrcl5x_,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:logo
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LogoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var logo_default = ComponentWithRoot;
export { logo_default as default };
