// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'monthly primary' | 'yearly' | 'monthly on-click' | 'yearly on-click' // Variant
 * click2?: Function // Click 2
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ZFADYJLF.js";
import { className, css, fonts } from "./chunks/chunk-7BNG6VRZ.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:monthly-yearly
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b5oH0OJfoD0vSBtWzCnU/tUbWLVn4gMXpatkhuJbJ/ukUMr75KR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["D4lCvHnkk", "y1YQGC72c", "rBWG9EkWH", "ncjQadXeD"];
var serializationHash = "framer-oYQJ0";
var variantClassNames = {
	D4lCvHnkk: "framer-v-fxk0jk",
	ncjQadXeD: "framer-v-nhy8rh",
	rBWG9EkWH: "framer-v-unhuia",
	y1YQGC72c: "framer-v-8prhtq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"monthly on-click": "rBWG9EkWH",
	"monthly primary": "D4lCvHnkk",
	"yearly on-click": "ncjQadXeD",
	yearly: "y1YQGC72c",
};
var getProps = ({ click2, height, id, width, ...props }) => {
	return {
		...props,
		IE6sfFa7G: click2 ?? props.IE6sfFa7G,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "D4lCvHnkk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		IE6sfFa7G,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "D4lCvHnkk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap14qqny9 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (IE6sfFa7G) {
			const res = await IE6sfFa7G(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["y1YQGC72c", "ncjQadXeD"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-fxk0jk",
							className3,
							classNames,
						)}
						data-framer-name={"monthly primary"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"D4lCvHnkk"}
						onTap={onTap14qqny9}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 6,
							borderBottomRightRadius: 6,
							borderTopLeftRadius: 6,
							borderTopRightRadius: 6,
							...style,
						}}
						variants={{
							ncjQadXeD: {
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							},
							rBWG9EkWH: {
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							},
						}}
						{...addPropertyOverrides(
							{
								ncjQadXeD: {
									"data-framer-name": "yearly on-click",
								},
								rBWG9EkWH: {
									"data-framer-name": "monthly on-click",
								},
								y1YQGC72c: {
									"data-framer-name": "yearly",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-j3im8y"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"if1zt5ZV2"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								opacity: 0.65,
							}}
							variants={{
								ncjQadXeD: {
									opacity: 1,
								},
								rBWG9EkWH: {
									opacity: 1,
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									ncjQadXeD: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-dmuy5d"}
													data-styles-preset={"LC6TE31cM"}
												>
													{"Yearly"}
												</motion.p>
											</React.Fragment>
										),
									},
									y1YQGC72c: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-dmuy5d"}
													data-styles-preset={"LC6TE31cM"}
												>
													{"Yearly"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-dmuy5d"}
									data-styles-preset={"LC6TE31cM"}
								>
									{"Monthly "}
								</motion.p>
							</React.Fragment>
						</RichText>
						{isDisplayed() && (
							<motion.div
								className={"framer-1ssb40a"}
								data-framer-name={"offer"}
								layoutDependency={layoutDependency}
								layoutId={"VjXNX0RJB"}
								style={{
									backgroundColor:
										"var(--token-aeb15aaf-db9c-447f-8383-662c7fda9c5a, rgba(240, 248, 255, 0.9))",
									borderBottomLeftRadius: 192,
									borderBottomRightRadius: 192,
									borderTopLeftRadius: 192,
									borderTopRightRadius: 192,
								}}
								variants={{
									ncjQadXeD: {
										backgroundColor:
											"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
									},
									y1YQGC72c: {
										backgroundColor:
											"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
									},
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-33gws5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"SDyxM2NEd"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											ncjQadXeD: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-dmuy5d"}
															data-styles-preset={"LC6TE31cM"}
														>
															{"Save 20% "}
														</motion.p>
													</React.Fragment>
												),
											},
											y1YQGC72c: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-dmuy5d"}
															data-styles-preset={"LC6TE31cM"}
														>
															{"Save 20% "}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-qbxcjn"}
											data-styles-preset={"nf0yFfa08"}
										>
											{"Save 20% "}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oYQJ0.framer-om5yrx, .framer-oYQJ0 .framer-om5yrx { display: block; }",
	".framer-oYQJ0.framer-fxk0jk { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 38px; justify-content: center; overflow: visible; padding: 8px 10px 8px 10px; position: relative; width: min-content; }",
	".framer-oYQJ0 .framer-j3im8y { flex: none; height: auto; pointer-events: none; position: relative; white-space: pre; width: auto; }",
	".framer-oYQJ0 .framer-1ssb40a { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 4px 10px 4px 10px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-oYQJ0 .framer-33gws5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css2,
	...css,
];
var FramerukUMr75KR = withCSS(Component, css3, "framer-oYQJ0");
var stdin_default = FramerukUMr75KR;
FramerukUMr75KR.displayName = "monthly & yearly";
FramerukUMr75KR.defaultProps = {
	height: 38,
	width: 77,
};
addPropertyControls(FramerukUMr75KR, {
	variant: {
		options: ["D4lCvHnkk", "y1YQGC72c", "rBWG9EkWH", "ncjQadXeD"],
		optionTitles: [
			"monthly primary",
			"yearly",
			"monthly on-click",
			"yearly on-click",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	IE6sfFa7G: {
		title: "Click 2",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerukUMr75KR,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:monthly-yearly
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "D4lCvHnkk",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MonthlyYearlyFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var monthly_yearly_default = ComponentWithRoot;
export { monthly_yearly_default as default };
