// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * role?: string // Role
 * review?: string // Review
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YLF6WDSY.js";
import { className, css, fonts } from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:review-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/k6rcrLRKxX0V37da4ksg/rI9DulC1lpoe55A3hIWS/nIzHdX8Y6.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCodeBoundaryForOverrides,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/3jWNybDD8BIiBFKvNzdM/2UgRiqUlzi1Wuugrf0Kl/Overflow_text.js
import { jsx as _jsx } from "react/jsx-runtime";
function withFourLineEllipsis(Component2) {
	return (props) => {
		const newStyle = {
			...props.style,
			display: "-webkit-box",
			WebkitBoxOrient: "vertical",
			overflow: "hidden",
			WebkitLineClamp: 4,
			textOverflow: "ellipsis",
		};
		return <Component2 {...props} style={newStyle} />;
	};
}

// /:https://framerusercontent.com/modules/k6rcrLRKxX0V37da4ksg/rI9DulC1lpoe55A3hIWS/nIzHdX8Y6.js
var RichTextWithFourLineEllipsis1nnnbvr = withCodeBoundaryForOverrides(
	RichText,
	{
		nodeId: "dCyczFE1Y",
		override: withFourLineEllipsis,
		scopeId: "nIzHdX8Y6",
	},
);
var serializationHash = "framer-BG4md";
var variantClassNames = {
	EkHvYBU_0: "framer-v-1j6uj9k",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	image,
	name1,
	review,
	role,
	width,
	...props
}) => {
	return {
		...props,
		eh4HJ5FRx: name1 ?? props.eh4HJ5FRx ?? "Name",
		UJrGavXuk: image ?? props.UJrGavXuk,
		uYNBzKkX9: role ?? props.uYNBzKkX9 ?? "Role",
		whgBZJChm: review ?? props.whgBZJChm ?? "Review text",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		UJrGavXuk,
		eh4HJ5FRx,
		uYNBzKkX9,
		whgBZJChm,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "EkHvYBU_0",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1j6uj9k",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"review"}
						layoutDependency={layoutDependency}
						layoutId={"EkHvYBU_0"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
					>
						<motion.div
							className={"framer-v0vzfd"}
							data-framer-name={"User Info"}
							layoutDependency={layoutDependency}
							layoutId={"ttzZbylJr"}
							style={{
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								boxShadow:
									"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2), inset 0px -1px 1px 0px rgba(207, 231, 255, 0.1)",
							}}
						>
							<motion.div
								className={"framer-bavkv0"}
								data-framer-name={"User image"}
								layoutDependency={layoutDependency}
								layoutId={"cfhpNdz9r"}
								style={{
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 89 + 4,
										),
										sizes: "50px",
										...toResponsiveImage(UJrGavXuk),
									}}
									className={"framer-9jylxi"}
									layoutDependency={layoutDependency}
									layoutId={"DtvU5BCki"}
									style={{
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-1ynzzp0"}
								data-framer-name={"User name + role"}
								layoutDependency={layoutDependency}
								layoutId={"ySAGRkBRL"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1w51wvt"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"eouJYU9Vg"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={eh4HJ5FRx}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1kvyxmc"}
											data-styles-preset={"n7RLEGRKm"}
										>
											{"Name"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1r8y1tt"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"rICESuT5i"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										opacity: 0.5,
									}}
									text={uYNBzKkX9}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1u349i7"}
											data-styles-preset={"rerWrmQ65"}
										>
											{"Role"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-caaqda"}
							data-framer-name={"Review text"}
							layoutDependency={layoutDependency}
							layoutId={"sMPl4lrX0"}
						>
							<RichTextWithFourLineEllipsis1nnnbvr
								__fromCanvasComponent={true}
								className={"framer-1nnnbvr"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"dCyczFE1Y"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 0.8,
								}}
								text={whgBZJChm}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"Review text"}
									</motion.p>
								</React.Fragment>
							</RichTextWithFourLineEllipsis1nnnbvr>
						</motion.div>
						<motion.div
							className={"framer-8ewljv"}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"ZgDXCXb5i"}
							style={{
								background:
									"radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) 0%, rgba(4, 7, 13, 0) 100%)",
								opacity: 0.1,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BG4md.framer-76hvef, .framer-BG4md .framer-76hvef { display: block; }",
	".framer-BG4md.framer-1j6uj9k { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 350px; will-change: var(--framer-will-change-override, transform); }",
	".framer-BG4md .framer-v0vzfd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 15px; position: relative; width: 100%; }",
	".framer-BG4md .framer-bavkv0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 4px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-BG4md .framer-9jylxi { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 50px); overflow: hidden; position: relative; width: 50px; will-change: var(--framer-will-change-override, transform); }",
	".framer-BG4md .framer-1ynzzp0 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-BG4md .framer-1w51wvt, .framer-BG4md .framer-1r8y1tt { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-BG4md .framer-caaqda { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 25px; position: relative; width: 100%; }",
	".framer-BG4md .framer-1nnnbvr { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-BG4md .framer-8ewljv { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	...css,
	...css2,
	'.framer-BG4md[data-border="true"]::after, .framer-BG4md [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramernIzHdX8Y6 = withCSS(Component, css3, "framer-BG4md");
var stdin_default = FramernIzHdX8Y6;
FramernIzHdX8Y6.displayName = "review card";
FramernIzHdX8Y6.defaultProps = {
	height: 164,
	width: 350,
};
addPropertyControls(FramernIzHdX8Y6, {
	UJrGavXuk: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	eh4HJ5FRx: {
		defaultValue: "Name",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	uYNBzKkX9: {
		defaultValue: "Role",
		displayTextArea: false,
		title: "Role",
		type: ControlType.String,
	},
	whgBZJChm: {
		defaultValue: "Review text",
		displayTextArea: true,
		title: "Review",
		type: ControlType.String,
	},
});
addFonts(
	FramernIzHdX8Y6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:review-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ReviewCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var review_card_default = ComponentWithRoot;
export { review_card_default as default };
