// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * discription?: string // discription
 * graphicVisible?: boolean // graphic visible
}} Props

 */
import {
	stdin_default,
	stdin_default2,
	stdin_default3 as stdin_default4,
	stdin_default4 as stdin_default5,
	stdin_default5 as stdin_default6,
	stdin_default6 as stdin_default8,
	stdin_default7 as stdin_default9,
	stdin_default8 as stdin_default10,
} from "./chunks/chunk-FUWIJPPX.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-OCDCCSSV.js";
import { stdin_default as stdin_default7 } from "./chunks/chunk-6JJTE674.js";
import { className, css, fonts } from "./chunks/chunk-2X2OXJIF.js";
import "./chunks/chunk-GD2KCKTC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:service-card-2
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/eKOijJIB2WCpBSIIMSAR/8MpFtmiWzcFuf3TNCRam/Ak69KrKVV.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/sN4jg2YHA0EGdp0Dgayy/S6YrzXVIbBZnlW6XtsxQ/XKggOoX7W.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Instance,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var IconCard2Fonts = getFonts(stdin_default10);
var cycleOrder = ["XlzFtPUDa", "mvzVcmWE1"];
var serializationHash = "framer-V7T9h";
var variantClassNames = {
	mvzVcmWE1: "framer-v-a1d5tc",
	XlzFtPUDa: "framer-v-xkti2v",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "XlzFtPUDa",
	"Variant 2": "mvzVcmWE1",
};
var getProps = ({
	height,
	icon1,
	icon2,
	icon3,
	icon4,
	icon5,
	icon6,
	icon7,
	id,
	mainIcon,
	width,
	...props
}) => {
	return {
		...props,
		GrM9cs7st: icon3 ?? props.GrM9cs7st ?? stdin_default,
		jal1JQOsr: icon7 ?? props.jal1JQOsr ?? stdin_default7,
		LFAK7DW16: mainIcon ?? props.LFAK7DW16 ?? stdin_default3,
		MpExg2QAW: icon4 ?? props.MpExg2QAW ?? stdin_default2,
		RBBYX1ioU: icon6 ?? props.RBBYX1ioU ?? stdin_default9,
		TZH3Sn7Fd: icon5 ?? props.TZH3Sn7Fd ?? stdin_default4,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XlzFtPUDa",
		xVZ0fRTEu: icon1 ?? props.xVZ0fRTEu ?? stdin_default5,
		zkcF8aPiI: icon2 ?? props.zkcF8aPiI ?? stdin_default8,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		LFAK7DW16,
		xVZ0fRTEu,
		zkcF8aPiI,
		GrM9cs7st,
		MpExg2QAW,
		TZH3Sn7Fd,
		RBBYX1ioU,
		jal1JQOsr,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XlzFtPUDa",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear5wtazb = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("mvzVcmWE1", true), 2e3);
	});
	const onAppear13gj76v = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("XlzFtPUDa", true), 2e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear5wtazb,
		mvzVcmWE1: onAppear13gj76v,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-xkti2v",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"XlzFtPUDa"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								mvzVcmWE1: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-8s7dck"}
							data-border={true}
							data-framer-name={"shape "}
							layoutDependency={layoutDependency}
							layoutId={"gjy5qf9ji"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow:
									"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2), 0px 7px 14px 0px rgba(166, 218, 255, 0.31)",
							}}
							transformTemplate={transformTemplate1}
						>
							<Instance
								animated={true}
								className={"framer-1uisht5"}
								Component={LFAK7DW16}
								layoutDependency={layoutDependency}
								layoutId={"vTI9_Mj6v"}
								style={{
									"--1m6trwb": 0.2,
									"--21h8s6":
										"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
									"--pgex8v": 1.5,
								}}
								transformTemplate={transformTemplate1}
							/>
						</motion.div>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 10}
						>
							<SmartComponentScopedContainer
								className={"framer-1o71tec-container"}
								layoutDependency={layoutDependency}
								layoutId={"zfR04H2Yc-container"}
								nodeId={"zfR04H2Yc"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 0.8,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										scale: 1.2,
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "zfR04H2Yc",
									layoutId: "zfR04H2Yc",
									NtGaM9Q7r: TZH3Sn7Fd,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 253) -
								74
							}
						>
							<SmartComponentScopedContainer
								className={"framer-42ejbz-container"}
								layoutDependency={layoutDependency}
								layoutId={"dRlwzHHjH-container"}
								nodeId={"dRlwzHHjH"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "dRlwzHHjH",
									layoutId: "dRlwzHHjH",
									NtGaM9Q7r: RBBYX1ioU,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 36}
						>
							<SmartComponentScopedContainer
								className={"framer-rn64x0-container"}
								layoutDependency={layoutDependency}
								layoutId={"CbyPTaRxM-container"}
								nodeId={"CbyPTaRxM"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 0.8,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										scale: 1.2,
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "CbyPTaRxM",
									layoutId: "CbyPTaRxM",
									NtGaM9Q7r: zkcF8aPiI,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 253) -
								79
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1niqny4-container"}
								layoutDependency={layoutDependency}
								layoutId={"hHBKGxaKj-container"}
								nodeId={"hHBKGxaKj"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 0.8,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										scale: 1.2,
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "hHBKGxaKj",
									layoutId: "hHBKGxaKj",
									NtGaM9Q7r: MpExg2QAW,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 36}
						>
							<SmartComponentScopedContainer
								className={"framer-vn40hj-container"}
								layoutDependency={layoutDependency}
								layoutId={"vx76rV7xZ-container"}
								nodeId={"vx76rV7xZ"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "vx76rV7xZ",
									layoutId: "vx76rV7xZ",
									NtGaM9Q7r: GrM9cs7st,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 47}
						>
							<SmartComponentScopedContainer
								className={"framer-1b4d14e-container"}
								layoutDependency={layoutDependency}
								layoutId={"pruUAvI1u-container"}
								nodeId={"pruUAvI1u"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "pruUAvI1u",
									layoutId: "pruUAvI1u",
									NtGaM9Q7r: jal1JQOsr,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								((componentViewport?.height || 253) * 0.4189723320158105 - 26)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-2a428l-container"}
								layoutDependency={layoutDependency}
								layoutId={"JlbiDhpyG-container"}
								nodeId={"JlbiDhpyG"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									WebkitFilter: "blur(0px)",
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "JlbiDhpyG",
									layoutId: "JlbiDhpyG",
									NtGaM9Q7r: stdin_default6,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 253) -
								100
							}
						>
							<SmartComponentScopedContainer
								className={"framer-42jy6v-container"}
								layoutDependency={layoutDependency}
								layoutId={"c421GxH0W-container"}
								nodeId={"c421GxH0W"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "c421GxH0W",
									layoutId: "c421GxH0W",
									NtGaM9Q7r: xVZ0fRTEu,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-17fpv58"}
							data-framer-name={"bg layer"}
							layoutDependency={layoutDependency}
							layoutId={"b9ktCelbh"}
							style={{
								backdropFilter: "blur(1px)",
								background:
									"radial-gradient(50% 50% at 50% 50%, var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28)) 0%, rgba(0, 0, 0, 0) 100%)",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								WebkitBackdropFilter: "blur(1px)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-V7T9h.framer-1mrvhtx, .framer-V7T9h .framer-1mrvhtx { display: block; }",
	".framer-V7T9h.framer-xkti2v { height: 253px; overflow: hidden; position: relative; width: 692px; }",
	".framer-V7T9h .framer-8s7dck { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 124px); left: 46%; overflow: hidden; position: absolute; top: 46%; width: 124px; will-change: var(--framer-will-change-override, transform); z-index: 2; }",
	".framer-V7T9h .framer-1uisht5 { flex: none; height: var(--framer-aspect-ratio-supported, 56px); left: 50%; position: absolute; top: 50%; width: 56px; }",
	".framer-V7T9h .framer-1o71tec-container { flex: none; height: 52px; position: absolute; right: 219px; top: 10px; width: 54px; }",
	".framer-V7T9h .framer-42ejbz-container { bottom: 22px; flex: none; height: 52px; position: absolute; right: 158px; width: 54px; }",
	".framer-V7T9h .framer-rn64x0-container { flex: none; height: 52px; left: 24px; position: absolute; top: 36px; width: 54px; }",
	".framer-V7T9h .framer-1niqny4-container { bottom: 27px; flex: none; height: 52px; left: 186px; position: absolute; width: 54px; }",
	".framer-V7T9h .framer-vn40hj-container { flex: none; height: 52px; left: 142px; position: absolute; top: 36px; width: 54px; }",
	".framer-V7T9h .framer-1b4d14e-container { flex: none; height: 52px; position: absolute; right: 62px; top: 47px; width: 54px; }",
	".framer-V7T9h .framer-2a428l-container { flex: none; height: 52px; position: absolute; right: 384px; top: calc(41.89723320158105% - 52px / 2); width: 54px; }",
	".framer-V7T9h .framer-42jy6v-container { bottom: 48px; flex: none; height: 52px; left: 27px; position: absolute; width: 54px; }",
	".framer-V7T9h .framer-17fpv58 { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
	'.framer-V7T9h[data-border="true"]::after, .framer-V7T9h [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerXKggOoX7W = withCSS(Component, css3, "framer-V7T9h");
var stdin_default11 = FramerXKggOoX7W;
FramerXKggOoX7W.displayName = "service 2";
FramerXKggOoX7W.defaultProps = {
	height: 253,
	width: 692,
};
addPropertyControls(FramerXKggOoX7W, {
	variant: {
		options: ["XlzFtPUDa", "mvzVcmWE1"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LFAK7DW16: {
		defaultValue: {
			identifier:
				"module:6E2CGo0e7Cc8gA9Pxqck/o74a7BK1ERiMNm6HcbIs/fhHgguzMk.js:default",
			moduleId: "6E2CGo0e7Cc8gA9Pxqck",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "main icon",
		type: ControlType.VectorSetItem,
	},
	xVZ0fRTEu: {
		defaultValue: {
			identifier:
				"module:L00S2RH1zp3gjUauADCR/l2t8UZfSu562suAZ9M6H/ylAoGfSL3.js:default",
			moduleId: "L00S2RH1zp3gjUauADCR",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 1",
		type: ControlType.VectorSetItem,
	},
	zkcF8aPiI: {
		defaultValue: {
			identifier:
				"module:Uzqkv2OV8vOM0tvVJuKZ/Wcbds34669567Myvr1Km/sYXjYwbRE.js:default",
			moduleId: "Uzqkv2OV8vOM0tvVJuKZ",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 2",
		type: ControlType.VectorSetItem,
	},
	GrM9cs7st: {
		defaultValue: {
			identifier:
				"module:3J2a9hSsfGA1vh4X7IJT/ksWmmn8Wkb1Y35lHCJxt/U4VlAAgoV.js:default",
			moduleId: "3J2a9hSsfGA1vh4X7IJT",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 3",
		type: ControlType.VectorSetItem,
	},
	MpExg2QAW: {
		defaultValue: {
			identifier:
				"module:4xQYlh6neffoT4xOa3iK/MgXhIs76CLAgMej2DxbG/s9Ir45kgf.js:default",
			moduleId: "4xQYlh6neffoT4xOa3iK",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 4",
		type: ControlType.VectorSetItem,
	},
	TZH3Sn7Fd: {
		defaultValue: {
			identifier:
				"module:kq8S957TBD9wLscySfuK/7xMcV7vp3MUd9K1ZeIOU/EzpB6oIKe.js:default",
			moduleId: "kq8S957TBD9wLscySfuK",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 5",
		type: ControlType.VectorSetItem,
	},
	RBBYX1ioU: {
		defaultValue: {
			identifier:
				"module:zcSotDXwC3ILDpYMuo5w/Yf8IivW8YMpET9VPAcuj/ciWRcWiCm.js:default",
			moduleId: "zcSotDXwC3ILDpYMuo5w",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 6",
		type: ControlType.VectorSetItem,
	},
	jal1JQOsr: {
		defaultValue: {
			identifier:
				"module:oMiuMYAdxzz5yk7pBqrm/FToqm3dwiHuJofBRASRI/Xx_sbLkzD.js:default",
			moduleId: "oMiuMYAdxzz5yk7pBqrm",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 7",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	FramerXKggOoX7W,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...IconCard2Fonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/eKOijJIB2WCpBSIIMSAR/8MpFtmiWzcFuf3TNCRam/Ak69KrKVV.js
var Service2Fonts = getFonts2(stdin_default11);
var serializationHash2 = "framer-gVXIX";
var variantClassNames2 = {
	QNvq1g3sk: "framer-v-btvl1c",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({
	discription,
	graphicVisible,
	height,
	id,
	title,
	width,
	...props
}) => {
	return {
		...props,
		hYZ_ToDgH: graphicVisible ?? props.hYZ_ToDgH ?? true,
		SM_hvNd8b:
			discription ??
			props.SM_hvNd8b ??
			"Automate workflows to streamline tasks, boost efficiency, andAutomate workflows to streamline tasks, boost efficiency, and save time save time",
		VfZk4rpBP: title ?? props.VfZk4rpBP ?? "Automated Workflows",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		VfZk4rpBP,
		SM_hvNd8b,
		hYZ_ToDgH,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "QNvq1g3sk",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-btvl1c",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"QNvq1g3sk"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						{hYZ_ToDgH && (
							<ComponentViewportProvider2
								height={253}
								width={`calc(${componentViewport?.width || "100vw"} - 58px)`}
								y={
									(componentViewport?.y || 0) +
									29 +
									(((componentViewport?.height || 420) - 58 - 535) / 2 + 0 + 0)
								}
							>
								<SmartComponentScopedContainer2
									className={"framer-z27gtl-container"}
									layoutDependency={layoutDependency}
									layoutId={"uK4BUYs_p-container"}
									nodeId={"uK4BUYs_p"}
									rendersWithMotion={true}
									scopeId={"Ak69KrKVV"}
								>
									{_jsx2(stdin_default11, {
										height: "100%",
										id: "uK4BUYs_p",
										layoutId: "uK4BUYs_p",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "XlzFtPUDa",
										width: "100%",
									})}
								</SmartComponentScopedContainer2>
							</ComponentViewportProvider2>
						)}
						<motion2.div
							className={"framer-fiktyg"}
							layoutDependency={layoutDependency}
							layoutId={"vVd6k8GbL"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-w74crf"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"QubfV3V5w"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={VfZk4rpBP}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-i6z8by"}
										data-styles-preset={"j3hccNIu_"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"Automated Workflows"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1umnd35"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"aBAxk5pY9"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 0.6,
								}}
								text={SM_hvNd8b}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
									>
										{
											"Automate workflows to streamline tasks, boost efficiency, andAutomate workflows to streamline tasks, boost efficiency, and save time save time"
										}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gVXIX.framer-eow2so, .framer-gVXIX .framer-eow2so { display: block; }",
	".framer-gVXIX.framer-btvl1c { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 29px; position: relative; width: 750px; }",
	".framer-gVXIX .framer-z27gtl-container { flex: none; height: 253px; position: relative; width: 100%; }",
	".framer-gVXIX .framer-fiktyg { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-gVXIX .framer-w74crf, .framer-gVXIX .framer-1umnd35 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
	...css2,
	'.framer-gVXIX[data-border="true"]::after, .framer-gVXIX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerAk69KrKVV = withCSS2(Component2, css4, "framer-gVXIX");
var stdin_default12 = FramerAk69KrKVV;
FramerAk69KrKVV.displayName = "service card 2";
FramerAk69KrKVV.defaultProps = {
	height: 420,
	width: 750,
};
addPropertyControls2(FramerAk69KrKVV, {
	VfZk4rpBP: {
		defaultValue: "Automated Workflows",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	SM_hvNd8b: {
		defaultValue:
			"Automate workflows to streamline tasks, boost efficiency, andAutomate workflows to streamline tasks, boost efficiency, and save time save time",
		displayTextArea: true,
		title: "discription",
		type: ControlType2.String,
	},
	hYZ_ToDgH: {
		defaultValue: true,
		title: "graphic visible",
		type: ControlType2.Boolean,
	},
});
addFonts2(
	FramerAk69KrKVV,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...Service2Fonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-card-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default12, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCard2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default12}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default12);
var service_card_2_default = ComponentWithRoot;
export { service_card_2_default as default };
