// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * mainIcon?: any // main icon
 * icon1?: any // icon 1
 * icon2?: any // icon 2
 * icon3?: any // icon 3
 * icon4?: any // icon 4
 * icon5?: any // icon 5
 * icon6?: any // icon 6
 * icon7?: any // icon 7
}} Props

 */
import {
	stdin_default,
	stdin_default2,
	stdin_default3 as stdin_default4,
	stdin_default4 as stdin_default5,
	stdin_default5 as stdin_default6,
	stdin_default6 as stdin_default8,
	stdin_default7 as stdin_default9,
	stdin_default8 as stdin_default10,
} from "./chunks/chunk-FUWIJPPX.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-OCDCCSSV.js";
import { stdin_default as stdin_default7 } from "./chunks/chunk-6JJTE674.js";
import "./chunks/chunk-GD2KCKTC.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:service-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3OGbU2hvlcGtzsotCg3J/7rmT14QxJE7MB5W5kbqt/XKggOoX7W.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Instance,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var IconCard2Fonts = getFonts(stdin_default10);
var cycleOrder = ["XlzFtPUDa", "mvzVcmWE1"];
var serializationHash = "framer-V7T9h";
var variantClassNames = {
	mvzVcmWE1: "framer-v-a1d5tc",
	XlzFtPUDa: "framer-v-xkti2v",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "XlzFtPUDa",
	"Variant 2": "mvzVcmWE1",
};
var getProps = ({
	height,
	icon1,
	icon2,
	icon3,
	icon4,
	icon5,
	icon6,
	icon7,
	id,
	mainIcon,
	width,
	...props
}) => {
	return {
		...props,
		GrM9cs7st: icon3 ?? props.GrM9cs7st ?? stdin_default,
		jal1JQOsr: icon7 ?? props.jal1JQOsr ?? stdin_default7,
		LFAK7DW16: mainIcon ?? props.LFAK7DW16 ?? stdin_default3,
		MpExg2QAW: icon4 ?? props.MpExg2QAW ?? stdin_default2,
		RBBYX1ioU: icon6 ?? props.RBBYX1ioU ?? stdin_default9,
		TZH3Sn7Fd: icon5 ?? props.TZH3Sn7Fd ?? stdin_default4,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XlzFtPUDa",
		xVZ0fRTEu: icon1 ?? props.xVZ0fRTEu ?? stdin_default5,
		zkcF8aPiI: icon2 ?? props.zkcF8aPiI ?? stdin_default8,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		LFAK7DW16,
		xVZ0fRTEu,
		zkcF8aPiI,
		GrM9cs7st,
		MpExg2QAW,
		TZH3Sn7Fd,
		RBBYX1ioU,
		jal1JQOsr,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XlzFtPUDa",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear5wtazb = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("mvzVcmWE1", true), 2e3);
	});
	const onAppear13gj76v = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("XlzFtPUDa", true), 2e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear5wtazb,
		mvzVcmWE1: onAppear13gj76v,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-xkti2v",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"XlzFtPUDa"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								mvzVcmWE1: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-8s7dck"}
							data-border={true}
							data-framer-name={"shape "}
							layoutDependency={layoutDependency}
							layoutId={"gjy5qf9ji"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow:
									"inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2), 0px 7px 14px 0px rgba(166, 218, 255, 0.31)",
							}}
							transformTemplate={transformTemplate1}
						>
							<Instance
								animated={true}
								className={"framer-1uisht5"}
								Component={LFAK7DW16}
								layoutDependency={layoutDependency}
								layoutId={"vTI9_Mj6v"}
								style={{
									"--1m6trwb": 0.2,
									"--21h8s6":
										"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
									"--pgex8v": 1.5,
								}}
								transformTemplate={transformTemplate1}
							/>
						</motion.div>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 10}
						>
							<SmartComponentScopedContainer
								className={"framer-1o71tec-container"}
								layoutDependency={layoutDependency}
								layoutId={"zfR04H2Yc-container"}
								nodeId={"zfR04H2Yc"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 0.8,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										scale: 1.2,
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "zfR04H2Yc",
									layoutId: "zfR04H2Yc",
									NtGaM9Q7r: TZH3Sn7Fd,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 253) -
								74
							}
						>
							<SmartComponentScopedContainer
								className={"framer-42ejbz-container"}
								layoutDependency={layoutDependency}
								layoutId={"dRlwzHHjH-container"}
								nodeId={"dRlwzHHjH"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "dRlwzHHjH",
									layoutId: "dRlwzHHjH",
									NtGaM9Q7r: RBBYX1ioU,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 36}
						>
							<SmartComponentScopedContainer
								className={"framer-rn64x0-container"}
								layoutDependency={layoutDependency}
								layoutId={"CbyPTaRxM-container"}
								nodeId={"CbyPTaRxM"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 0.8,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										scale: 1.2,
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "CbyPTaRxM",
									layoutId: "CbyPTaRxM",
									NtGaM9Q7r: zkcF8aPiI,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 253) -
								79
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1niqny4-container"}
								layoutDependency={layoutDependency}
								layoutId={"hHBKGxaKj-container"}
								nodeId={"hHBKGxaKj"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 0.8,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										scale: 1.2,
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "hHBKGxaKj",
									layoutId: "hHBKGxaKj",
									NtGaM9Q7r: MpExg2QAW,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 36}
						>
							<SmartComponentScopedContainer
								className={"framer-vn40hj-container"}
								layoutDependency={layoutDependency}
								layoutId={"vx76rV7xZ-container"}
								nodeId={"vx76rV7xZ"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "vx76rV7xZ",
									layoutId: "vx76rV7xZ",
									NtGaM9Q7r: GrM9cs7st,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={(componentViewport?.y || 0) + 47}
						>
							<SmartComponentScopedContainer
								className={"framer-1b4d14e-container"}
								layoutDependency={layoutDependency}
								layoutId={"pruUAvI1u-container"}
								nodeId={"pruUAvI1u"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "pruUAvI1u",
									layoutId: "pruUAvI1u",
									NtGaM9Q7r: jal1JQOsr,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								((componentViewport?.height || 253) * 0.4189723320158105 - 26)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-2a428l-container"}
								layoutDependency={layoutDependency}
								layoutId={"JlbiDhpyG-container"}
								nodeId={"JlbiDhpyG"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									WebkitFilter: "blur(0px)",
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "JlbiDhpyG",
									layoutId: "JlbiDhpyG",
									NtGaM9Q7r: stdin_default6,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={52}
							width={"54px"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 253) -
								100
							}
						>
							<SmartComponentScopedContainer
								className={"framer-42jy6v-container"}
								layoutDependency={layoutDependency}
								layoutId={"c421GxH0W-container"}
								nodeId={"c421GxH0W"}
								rendersWithMotion={true}
								scopeId={"XKggOoX7W"}
								style={{
									filter: "blur(0px)",
									scale: 1.2,
									WebkitFilter: "blur(0px)",
								}}
								variants={{
									mvzVcmWE1: {
										filter: "blur(1px)",
										scale: 0.8,
										WebkitFilter: "blur(1px)",
									},
								}}
							>
								{_jsx(stdin_default10, {
									height: "100%",
									id: "c421GxH0W",
									layoutId: "c421GxH0W",
									NtGaM9Q7r: xVZ0fRTEu,
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-17fpv58"}
							data-framer-name={"bg layer"}
							layoutDependency={layoutDependency}
							layoutId={"b9ktCelbh"}
							style={{
								backdropFilter: "blur(1px)",
								background:
									"radial-gradient(50% 50% at 50% 50%, var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28)) 0%, rgba(0, 0, 0, 0) 100%)",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								WebkitBackdropFilter: "blur(1px)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-V7T9h.framer-1mrvhtx, .framer-V7T9h .framer-1mrvhtx { display: block; }",
	".framer-V7T9h.framer-xkti2v { height: 253px; overflow: hidden; position: relative; width: 692px; }",
	".framer-V7T9h .framer-8s7dck { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 124px); left: 46%; overflow: hidden; position: absolute; top: 46%; width: 124px; will-change: var(--framer-will-change-override, transform); z-index: 2; }",
	".framer-V7T9h .framer-1uisht5 { flex: none; height: var(--framer-aspect-ratio-supported, 56px); left: 50%; position: absolute; top: 50%; width: 56px; }",
	".framer-V7T9h .framer-1o71tec-container { flex: none; height: 52px; position: absolute; right: 219px; top: 10px; width: 54px; }",
	".framer-V7T9h .framer-42ejbz-container { bottom: 22px; flex: none; height: 52px; position: absolute; right: 158px; width: 54px; }",
	".framer-V7T9h .framer-rn64x0-container { flex: none; height: 52px; left: 24px; position: absolute; top: 36px; width: 54px; }",
	".framer-V7T9h .framer-1niqny4-container { bottom: 27px; flex: none; height: 52px; left: 186px; position: absolute; width: 54px; }",
	".framer-V7T9h .framer-vn40hj-container { flex: none; height: 52px; left: 142px; position: absolute; top: 36px; width: 54px; }",
	".framer-V7T9h .framer-1b4d14e-container { flex: none; height: 52px; position: absolute; right: 62px; top: 47px; width: 54px; }",
	".framer-V7T9h .framer-2a428l-container { flex: none; height: 52px; position: absolute; right: 384px; top: calc(41.89723320158105% - 52px / 2); width: 54px; }",
	".framer-V7T9h .framer-42jy6v-container { bottom: 48px; flex: none; height: 52px; left: 27px; position: absolute; width: 54px; }",
	".framer-V7T9h .framer-17fpv58 { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
	'.framer-V7T9h[data-border="true"]::after, .framer-V7T9h [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerXKggOoX7W = withCSS(Component, css, "framer-V7T9h");
var stdin_default11 = FramerXKggOoX7W;
FramerXKggOoX7W.displayName = "service 2";
FramerXKggOoX7W.defaultProps = {
	height: 253,
	width: 692,
};
addPropertyControls(FramerXKggOoX7W, {
	variant: {
		options: ["XlzFtPUDa", "mvzVcmWE1"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	LFAK7DW16: {
		defaultValue: {
			identifier:
				"module:6E2CGo0e7Cc8gA9Pxqck/o74a7BK1ERiMNm6HcbIs/fhHgguzMk.js:default",
			moduleId: "6E2CGo0e7Cc8gA9Pxqck",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "main icon",
		type: ControlType.VectorSetItem,
	},
	xVZ0fRTEu: {
		defaultValue: {
			identifier:
				"module:L00S2RH1zp3gjUauADCR/l2t8UZfSu562suAZ9M6H/ylAoGfSL3.js:default",
			moduleId: "L00S2RH1zp3gjUauADCR",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 1",
		type: ControlType.VectorSetItem,
	},
	zkcF8aPiI: {
		defaultValue: {
			identifier:
				"module:Uzqkv2OV8vOM0tvVJuKZ/Wcbds34669567Myvr1Km/sYXjYwbRE.js:default",
			moduleId: "Uzqkv2OV8vOM0tvVJuKZ",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 2",
		type: ControlType.VectorSetItem,
	},
	GrM9cs7st: {
		defaultValue: {
			identifier:
				"module:3J2a9hSsfGA1vh4X7IJT/ksWmmn8Wkb1Y35lHCJxt/U4VlAAgoV.js:default",
			moduleId: "3J2a9hSsfGA1vh4X7IJT",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 3",
		type: ControlType.VectorSetItem,
	},
	MpExg2QAW: {
		defaultValue: {
			identifier:
				"module:4xQYlh6neffoT4xOa3iK/MgXhIs76CLAgMej2DxbG/s9Ir45kgf.js:default",
			moduleId: "4xQYlh6neffoT4xOa3iK",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 4",
		type: ControlType.VectorSetItem,
	},
	TZH3Sn7Fd: {
		defaultValue: {
			identifier:
				"module:kq8S957TBD9wLscySfuK/7xMcV7vp3MUd9K1ZeIOU/EzpB6oIKe.js:default",
			moduleId: "kq8S957TBD9wLscySfuK",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 5",
		type: ControlType.VectorSetItem,
	},
	RBBYX1ioU: {
		defaultValue: {
			identifier:
				"module:zcSotDXwC3ILDpYMuo5w/Yf8IivW8YMpET9VPAcuj/ciWRcWiCm.js:default",
			moduleId: "zcSotDXwC3ILDpYMuo5w",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 6",
		type: ControlType.VectorSetItem,
	},
	jal1JQOsr: {
		defaultValue: {
			identifier:
				"module:oMiuMYAdxzz5yk7pBqrm/FToqm3dwiHuJofBRASRI/Xx_sbLkzD.js:default",
			moduleId: "oMiuMYAdxzz5yk7pBqrm",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "icon 7",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	FramerXKggOoX7W,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...IconCard2Fonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XlzFtPUDa",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default11, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Service2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default11}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default11);
var service_2_default = ComponentWithRoot;
export { service_2_default as default };
