// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * value?: number // value
 * valueText?: string // value text
}} Props

 */
import { stdin_default } from "./chunks/chunk-X7MHXBZO.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-DE2IIEG7.js";
import { className, css, fonts } from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:stat-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tZ3jjQnMd3PFO2Q6w2wQ/a8uiyqnbrVSxW5WOoMFi/BiOqFwtp3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var AnimatedCounterFonts = getFonts(stdin_default);
var serializationHash = "framer-baGja";
var variantClassNames = {
	TgdKycAjc: "framer-v-olu05p",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, value, valueText, width, ...props }) => {
	return {
		...props,
		DOwDAusV0: valueText ?? props.DOwDAusV0 ?? "Happy customers",
		LASfSWugG: value ?? props.LASfSWugG ?? 60,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		LASfSWugG,
		DOwDAusV0,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "TgdKycAjc",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-olu05p",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"TgdKycAjc"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1tfxao4"}
							data-framer-name={"count"}
							layoutDependency={layoutDependency}
							layoutId={"FEjqfBu44"}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-2lg9ug-container"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"BBQMbAdO6-container"}
									nodeId={"BBQMbAdO6"}
									rendersWithMotion={true}
									scopeId={"BiOqFwtp3"}
								>
									{_jsx(stdin_default, {
										color:
											"var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255))",
										duration: 2,
										fontFamily: "Inter",
										fontSize: 32,
										from: 0,
										height: "100%",
										id: "BBQMbAdO6",
										layoutId: "BBQMbAdO6",
										lineHeight: 1,
										to: LASfSWugG,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-12594so"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"FiatXWTLw"}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-1y9oj5s"}
										data-styles-preset={"fkjHG1SJt"}
									>
										{"%"}
									</motion.h3>
								</React.Fragment>
							</RichText>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1wxgtcc"}
							data-framer-name={"Text"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"Iw0WAG7fy"}
							text={DOwDAusV0}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1kvyxmc"}
									data-styles-preset={"n7RLEGRKm"}
									style={{
										"--framer-text-alignment": "center",
									}}
								>
									{"Happy customers"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-6z9thu"}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"jitx3qCTA"}
							style={{
								background:
									'radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) /* {"name":"grey blue"} */ 0%, rgba(4, 7, 13, 0) 100%)',
								opacity: 0.1,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-baGja.framer-rpmye5, .framer-baGja .framer-rpmye5 { display: block; }",
	".framer-baGja.framer-olu05p { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: wrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 20px; position: relative; width: 182px; will-change: var(--framer-will-change-override, transform); }",
	".framer-baGja .framer-1tfxao4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-baGja .framer-2lg9ug-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-baGja .framer-12594so { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-baGja .framer-1wxgtcc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-baGja .framer-6z9thu { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-baGja.framer-olu05p, .framer-baGja .framer-1tfxao4 { gap: 0px; } .framer-baGja.framer-olu05p > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-baGja.framer-olu05p > :first-child { margin-top: 0px; } .framer-baGja.framer-olu05p > :last-child { margin-bottom: 0px; } .framer-baGja .framer-1tfxao4 > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-baGja .framer-1tfxao4 > :first-child { margin-left: 0px; } .framer-baGja .framer-1tfxao4 > :last-child { margin-right: 0px; } }",
	...css2,
	...css,
	'.framer-baGja[data-border="true"]::after, .framer-baGja [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerBiOqFwtp3 = withCSS(Component, css3, "framer-baGja");
var stdin_default2 = FramerBiOqFwtp3;
FramerBiOqFwtp3.displayName = "Stat card";
FramerBiOqFwtp3.defaultProps = {
	height: 107,
	width: 182,
};
addPropertyControls(FramerBiOqFwtp3, {
	LASfSWugG: {
		defaultValue: 60,
		min: 0,
		step: 1,
		title: "value",
		type: ControlType.Number,
	},
	DOwDAusV0: {
		defaultValue: "Happy customers",
		displayTextArea: false,
		title: "value text",
		type: ControlType.String,
	},
});
addFonts(
	FramerBiOqFwtp3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...AnimatedCounterFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:stat-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StatCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var stat_card_default = ComponentWithRoot;
export { stat_card_default as default };
