// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'desktop - animate1' | 'mobile' | 'tablet' // Variant
 * icon?: any // Icon
 * title?: string // Title
 * discription?: string // discription
}} Props

 */
import { stdin_default } from "./chunks/chunk-OCDCCSSV.js";
import { className, css, fonts } from "./chunks/chunk-2X2OXJIF.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:strategy-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wY1ZMrSBFPvhIlhQYGIj/a88Gzbo4huXPDppz0C0R/zDv36VPPW.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/QtubL7OWzZSmpCU5MSIM/t21Ot6nB55jL0htOe6fC/eP8wLFDME.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		K5AAorpEW: fill ?? props.K5AAorpEW ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		K5AAorpEW,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-1loVP", className3)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--esondr": K5AAorpEW,
				...style,
			}}
		/>
	);
});
var css3 = [
	`.framer-1loVP { aspect-ratio: 1; background-color: var(--esondr); mask-image: url('data:image/svg+xml,<svg aria-label="Stacked Bar Chart" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 4 0 L 0 0 L 0 11 L 4 11 Z" fill="var(--esondr, rgb(0,0,0))" height="11px" id="RLkBCePZz" opacity="1" transform="translate(4 9)" width="4px"/><path d="M 4 0 L 0 0 L 0 4 L 4 4 Z" fill="var(--esondr, rgb(0,0,0))" height="4px" id="snfZ60enM" opacity="1" transform="translate(4 4)" width="4px"/><path d="M 4 0 L 0 0 L 0 4 L 4 4 Z" fill="var(--esondr, rgb(0,0,0))" height="4px" id="HVw0hsZ9Z" opacity="1" transform="translate(10 7)" width="4px"/><path d="M 4 0 L 0 0 L 0 4 L 4 4 Z" fill="var(--esondr, rgb(0,0,0))" height="4px" id="Digbyr524" opacity="1" transform="translate(16 10)" width="4px"/><path d="M 4 0 L 0 0 L 0 5 L 4 5 Z" fill="var(--esondr, rgb(0,0,0))" height="5px" id="JYVHcFamn" opacity="1" transform="translate(16 15)" width="4px"/><path d="M 4 0 L 0 0 L 0 8 L 4 8 Z" fill="var(--esondr, rgb(0,0,0))" height="8px" id="JQfdfrYDX" opacity="1" transform="translate(10 12)" width="4px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-1loVP");
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	K5AAorpEW: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/wY1ZMrSBFPvhIlhQYGIj/a88Gzbo4huXPDppz0C0R/zDv36VPPW.js
var SparkleFonts = getFonts(stdin_default);
var cycleOrder = ["yVZnp15uS", "eXMuVnn9o", "vnJq_5ns2", "ZfnGExy68"];
var serializationHash = "framer-QiXrN";
var variantClassNames = {
	eXMuVnn9o: "framer-v-e55z0v",
	vnJq_5ns2: "framer-v-qaayd",
	yVZnp15uS: "framer-v-1ybao5f",
	ZfnGExy68: "framer-v-13vi1dh",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"desktop - animate1": "eXMuVnn9o",
	desktop: "yVZnp15uS",
	mobile: "vnJq_5ns2",
	tablet: "ZfnGExy68",
};
var getProps2 = ({ discription, height, icon, id, title, width, ...props }) => {
	return {
		...props,
		I0KtDm67s:
			discription ??
			props.I0KtDm67s ??
			"Join a community of satisfied clients benefiting from our",
		jm45WP_eY: icon ?? props.jm45WP_eY ?? stdin_default2,
		jxpw6yvEh: title ?? props.jxpw6yvEh ?? "98% Client Success Rate",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yVZnp15uS",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		jm45WP_eY,
		jxpw6yvEh,
		I0KtDm67s,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yVZnp15uS",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearlxsp38 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("eXMuVnn9o", true), 2e3);
	});
	const onAppear11g5ed3 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("yVZnp15uS", true), 500);
	});
	useOnVariantChange(baseVariant, {
		default: onAppearlxsp38,
		eXMuVnn9o: onAppear11g5ed3,
		vnJq_5ns2: void 0,
		ZfnGExy68: void 0,
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["vnJq_5ns2", "ZfnGExy68"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1ybao5f",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"desktop"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"yVZnp15uS"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								eXMuVnn9o: {
									"data-framer-name": "desktop - animate1",
								},
								vnJq_5ns2: {
									"data-framer-name": "mobile",
									"data-highlight": void 0,
								},
								ZfnGExy68: {
									"data-framer-name": "tablet",
									"data-highlight": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-3j070i"}
							data-border={true}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"LdW5xL4Md"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
								rotate: 36,
							}}
							variants={{
								vnJq_5ns2: {
									rotate: 14,
								},
								ZfnGExy68: {
									rotate: 14,
								},
							}}
						/>
						<motion2.div
							className={"framer-179rics"}
							data-border={true}
							data-framer-name={"shape "}
							layoutDependency={layoutDependency}
							layoutId={"ldYzOL4PP"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							}}
							{...addPropertyOverrides(
								{
									vnJq_5ns2: {
										transformTemplate: transformTemplate1,
									},
									ZfnGExy68: {
										transformTemplate: transformTemplate2,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{_jsx2(stdin_default, {
								animated: true,
								className: "framer-l33j4s",
								layoutDependency,
								layoutId: "cv0m3hXU8",
								style: {
									"--1m6trwb": 0.2,
									"--21h8s6":
										"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
									"--pgex8v": 1,
									opacity: 0.8,
								},
								transformTemplate: transformTemplate2,
							})}
						</motion2.div>
						<motion2.div
							className={"framer-1f6vwh3"}
							data-border={true}
							data-framer-name={"shape "}
							layoutDependency={layoutDependency}
							layoutId={"ODNIYiZUU"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							}}
							{...addPropertyOverrides(
								{
									vnJq_5ns2: {
										transformTemplate: transformTemplate1,
									},
									ZfnGExy68: {
										transformTemplate: transformTemplate2,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Instance
								animated={true}
								className={"framer-1w0pxj8"}
								Component={jm45WP_eY}
								layoutDependency={layoutDependency}
								layoutId={"hLoe39Qz3"}
								style={{
									"--esondr":
										"var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7))",
								}}
								transformTemplate={transformTemplate2}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-d5juqz"}
							data-framer-name={"Text Container"}
							layoutDependency={layoutDependency}
							layoutId={"omIUXUdAP"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1p6hi4j"}
								data-framer-name={"Heading"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"fU26K2SMC"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={jxpw6yvEh}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-i6z8by"}
										data-styles-preset={"j3hccNIu_"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"98% Client Success Rate"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-fhb0pa"}
								data-framer-name={"Paragraph"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"bONiFd7_n"}
								style={{
									"--framer-paragraph-spacing": "0px",
									opacity: 0.6,
								}}
								text={I0KtDm67s}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
									>
										{
											"Join a community of satisfied clients benefiting from our"
										}
									</motion2.p>
								</React2.Fragment>
							</RichText>
						</motion2.div>
						<motion2.div
							className={"framer-nbs91u"}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"rMW7QfR4c"}
							style={{
								background:
									"radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) 0%, rgba(4, 7, 13, 0) 100%)",
								opacity: 0.1,
							}}
						/>
						<motion2.div
							className={"framer-1xtmcy7"}
							data-border={true}
							data-framer-name={"shape "}
							layoutDependency={layoutDependency}
							layoutId={"Ku2i86Tjj"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							}}
						/>
						<motion2.div
							className={"framer-k0wbi2"}
							data-border={true}
							data-framer-name={"shape "}
							layoutDependency={layoutDependency}
							layoutId={"O4QQDnwL6"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							}}
							transformTemplate={transformTemplate1}
							{...addPropertyOverrides(
								{
									vnJq_5ns2: {
										transformTemplate: void 0,
									},
									ZfnGExy68: {
										transformTemplate: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						{isDisplayed() && (
							<motion2.div
								className={"framer-vraewb"}
								data-border={true}
								data-framer-name={"shape "}
								layoutDependency={layoutDependency}
								layoutId={"zC6n9VKxx"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor:
										"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
									boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
								}}
								transformTemplate={transformTemplate1}
							/>
						)}
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QiXrN.framer-q9836o, .framer-QiXrN .framer-q9836o { display: block; }",
	".framer-QiXrN.framer-1ybao5f { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 359px; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 367px; will-change: var(--framer-will-change-override, transform); }",
	".framer-QiXrN .framer-3j070i { aspect-ratio: 23 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 6px); left: 91px; overflow: hidden; position: absolute; top: 91px; width: 137px; z-index: 1; }",
	".framer-QiXrN .framer-179rics { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 124px); left: 184px; overflow: hidden; position: absolute; top: 106px; width: 124px; will-change: var(--framer-will-change-override, transform); z-index: 2; }",
	".framer-QiXrN .framer-l33j4s { flex: none; height: var(--framer-aspect-ratio-supported, 56px); left: 50%; position: absolute; top: 50%; width: 56px; }",
	".framer-QiXrN .framer-1f6vwh3 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 84px); left: 60px; overflow: hidden; position: absolute; top: 20px; width: 84px; will-change: var(--framer-will-change-override, transform); z-index: 2; }",
	".framer-QiXrN .framer-1w0pxj8 { flex: none; height: var(--framer-aspect-ratio-supported, 48px); left: 50%; position: absolute; top: 50%; width: 48px; }",
	".framer-QiXrN .framer-d5juqz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 30px; position: relative; width: 100%; z-index: 3; }",
	".framer-QiXrN .framer-1p6hi4j { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-QiXrN .framer-fhb0pa { flex: none; height: auto; max-width: 600px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-QiXrN .framer-nbs91u { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	".framer-QiXrN .framer-1xtmcy7 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 35px); left: 77px; overflow: hidden; position: absolute; top: 145px; width: 35px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-QiXrN .framer-k0wbi2 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); left: 62%; overflow: hidden; position: absolute; top: 140px; width: 22px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-QiXrN .framer-vraewb { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); left: 32%; overflow: hidden; position: absolute; top: 58px; width: 22px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-QiXrN.framer-v-e55z0v.framer-1ybao5f { aspect-ratio: 1.0222841225626742 / 1; height: var(--framer-aspect-ratio-supported, 359px); }",
	".framer-QiXrN.framer-v-e55z0v .framer-k0wbi2 { left: 31%; top: 58px; }",
	".framer-QiXrN.framer-v-e55z0v .framer-vraewb { left: 58%; top: 129px; }",
	".framer-QiXrN.framer-v-qaayd.framer-1ybao5f { width: 330px; }",
	".framer-QiXrN.framer-v-qaayd .framer-3j070i { aspect-ratio: unset; height: 6px; left: calc(47.272727272727295% - 51.515151515151516% / 2); top: 92px; width: 52%; }",
	".framer-QiXrN.framer-v-qaayd .framer-179rics { aspect-ratio: 0.992 / 1; height: var(--framer-aspect-ratio-supported, 108px); left: 69%; top: 70px; width: 107px; }",
	".framer-QiXrN.framer-v-qaayd .framer-1f6vwh3 { height: var(--framer-aspect-ratio-supported, 80px); left: 22%; top: 30px; width: 80px; }",
	".framer-QiXrN.framer-v-qaayd .framer-d5juqz, .framer-QiXrN.framer-v-13vi1dh .framer-d5juqz { gap: 4px; padding: 24px; }",
	".framer-QiXrN.framer-v-qaayd .framer-1xtmcy7 { height: var(--framer-aspect-ratio-supported, 31px); left: 70px; top: 162px; width: 31px; }",
	".framer-QiXrN.framer-v-qaayd .framer-k0wbi2, .framer-QiXrN.framer-v-13vi1dh .framer-k0wbi2 { height: var(--framer-aspect-ratio-supported, 28px); left: unset; right: 39px; top: 16px; width: 28px; }",
	".framer-QiXrN.framer-v-13vi1dh.framer-1ybao5f { width: 365px; }",
	".framer-QiXrN.framer-v-13vi1dh .framer-3j070i { aspect-ratio: unset; height: 6px; left: calc(46.52862362971988% - 45.55420219244824% / 2); top: calc(27.323943661971857% - 6px / 2); width: 46%; }",
	".framer-QiXrN.framer-v-13vi1dh .framer-179rics { aspect-ratio: 0.992 / 1; height: var(--framer-aspect-ratio-supported, 108px); left: 69%; top: 35%; width: 107px; }",
	".framer-QiXrN.framer-v-13vi1dh .framer-l33j4s { height: var(--framer-aspect-ratio-supported, 200px); }",
	".framer-QiXrN.framer-v-13vi1dh .framer-1f6vwh3 { height: var(--framer-aspect-ratio-supported, 81px); left: 22%; top: 20%; width: 80px; }",
	".framer-QiXrN.framer-v-13vi1dh .framer-1xtmcy7 { height: var(--framer-aspect-ratio-supported, 32px); left: 70px; top: 162px; width: 31px; }",
	...css,
	...css2,
	'.framer-QiXrN[data-border="true"]::after, .framer-QiXrN [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerzDv36VPPW = withCSS2(Component2, css4, "framer-QiXrN");
var stdin_default3 = FramerzDv36VPPW;
FramerzDv36VPPW.displayName = "Strategy Card";
FramerzDv36VPPW.defaultProps = {
	height: 359,
	width: 367,
};
addPropertyControls2(FramerzDv36VPPW, {
	variant: {
		options: ["yVZnp15uS", "eXMuVnn9o", "vnJq_5ns2", "ZfnGExy68"],
		optionTitles: ["desktop", "desktop - animate1", "mobile", "tablet"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	jm45WP_eY: {
		defaultValue: {
			identifier:
				"module:QtubL7OWzZSmpCU5MSIM/t21Ot6nB55jL0htOe6fC/eP8wLFDME.js:default",
			moduleId: "QtubL7OWzZSmpCU5MSIM",
		},
		setModuleId: "JIScivAkNLgXrcOUxHXD",
		title: "Icon",
		type: ControlType2.VectorSetItem,
	},
	jxpw6yvEh: {
		defaultValue: "98% Client Success Rate",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	I0KtDm67s: {
		defaultValue: "Join a community of satisfied clients benefiting from our",
		displayTextArea: true,
		placeholder: "",
		title: "discription",
		type: ControlType2.String,
	},
});
addFonts(
	FramerzDv36VPPW,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SparkleFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:strategy-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "vnJq_5ns2",
	xl: "yVZnp15uS",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StrategyCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var strategy_card_default = ComponentWithRoot;
export { strategy_card_default as default };
