// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * name?: string // name
 * roles?: string // roles
 * twitterLink?: string // twitter link
 * instagramLink?: string // instagram link
 * linkedinLink?: string // linkedin link
 * profilePic?: {src: string, srcSet?: string, alt?: string} // profile pic
}} Props

 */
import { stdin_default } from "./chunks/chunk-PQK5NHI5.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YLF6WDSY.js";
import { className, css, fonts } from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:team-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4WcfS8vT7iAaztVXlcHj/9Yj5dSIAYgAphDjBUcc3/rQoyl_iEe.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS3,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/JNI0unvKLnSNOjYgWQPe/cFK4x7HnGbxoZXkZNw5W/hNcHJzSkR.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0.75 18 C 0.336 18 0 17.664 0 17.25 L 0 0.75 C 0 0.336 0.336 0 0.75 0 L 17.25 0 C 17.664 0 18 0.336 18 0.75 L 18 17.25 C 18 17.664 17.664 18 17.25 18 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="ubm8tT7Gs" transform="translate(3 3)" width="18px"/><path d="M 0.75 18 C 0.336 18 0 17.664 0 17.25 L 0 0.75 C 0 0.336 0.336 0 0.75 0 L 17.25 0 C 17.664 0 18 0.336 18 0.75 L 18 17.25 C 18 17.664 17.664 18 17.25 18 Z" fill="transparent" height="18px" id="uLIbokj1X" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 0 L 0 6" fill="transparent" height="6px" id="wcL4Xtw6S" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(11.25 10.5)" width="1px"/><path d="M 0 0 L 0 6" fill="transparent" height="6px" id="haFqKG9T6" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 10.5)" width="1px"/><path d="M 0 2.625 C 0 1.175 1.175 0 2.625 0 C 4.075 0 5.25 1.175 5.25 2.625 L 5.25 6" fill="transparent" height="6px" id="ldXP7NTX2" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(11.25 10.5)" width="5.25px"/><path d="M 0 1.125 C 0 0.504 0.504 0 1.125 0 C 1.746 0 2.25 0.504 2.25 1.125 C 2.25 1.746 1.746 2.25 1.125 2.25 C 0.504 2.25 0 1.746 0 1.125 Z" fill="var(--21h8s6, rgb(0, 0, 0))" height="2.25px" id="M86o3vn0T" transform="translate(7.125 6.75)" width="2.25px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("4033599021", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-qVh2c", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css3 = [
	`.framer-qVh2c { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css3, "framer-qVh2c");
Icon.displayName = "Linkedin Logo";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/PtxaBiSAA5V6LvrpAt6G/EsR1AqByikNQR8Cp2V8c/UD0eTfbk_.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var mask2 = "var(--framer-icon-mask)";
var Base2 = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion2.create(Base2);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG2>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.5 0 L 4.5 0 C 2.015 0 0 2.015 0 4.5 L 0 13.5 C 0 15.985 2.015 18 4.5 18 L 13.5 18 C 15.985 18 18 15.985 18 13.5 L 18 4.5 C 18 2.015 15.985 0 13.5 0 Z M 9 12.75 C 6.929 12.75 5.25 11.071 5.25 9 C 5.25 6.929 6.929 5.25 9 5.25 C 11.071 5.25 12.75 6.929 12.75 9 C 12.75 11.071 11.071 12.75 9 12.75 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="SuXKGhab5" transform="translate(3 3)" width="18px"/><path d="M 4.5 18 C 2.015 18 0 15.985 0 13.5 L 0 4.5 C 0 2.015 2.015 0 4.5 0 L 13.5 0 C 15.985 0 18 2.015 18 4.5 L 18 13.5 C 18 15.985 15.985 18 13.5 18 Z" fill="transparent" height="18px" id="vvJ8FLDVj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 3.75 C 0 1.679 1.679 0 3.75 0 C 5.821 0 7.5 1.679 7.5 3.75 C 7.5 5.821 5.821 7.5 3.75 7.5 C 1.679 7.5 0 5.821 0 3.75 Z" fill="transparent" height="7.5px" id="Q3v7fjWhv" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 8.25)" width="7.5px"/><path d="M 0 1.125 C 0 0.504 0.504 0 1.125 0 C 1.746 0 2.25 0.504 2.25 1.125 C 2.25 1.746 1.746 2.25 1.125 2.25 C 0.504 2.25 0 1.746 0 1.125 Z" fill="var(--21h8s6, rgb(0, 0, 0))" height="2.25px" id="VxeO4Hprj" transform="translate(15.75 6)" width="2.25px"/></svg>';
var getProps2 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate2("942143898", svg2);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-SHCqu", className3)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG2>
	);
});
var css4 = [
	`.framer-SHCqu { -webkit-mask: ${mask2}; aspect-ratio: 1; display: block; mask: ${mask2}; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css4, "framer-SHCqu");
Icon2.displayName = "Instagram Logo";
var stdin_default3 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType2.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/4WcfS8vT7iAaztVXlcHj/9Yj5dSIAYgAphDjBUcc3/rQoyl_iEe.js
var XLogoFonts = getFonts(stdin_default);
var InstagramLogoFonts = getFonts(stdin_default3);
var LinkedinLogoFonts = getFonts(stdin_default2);
var serializationHash = "framer-eRKLk";
var variantClassNames = {
	tvxPYrVDn: "framer-v-prjzlj",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React3.Fragment);
var getProps3 = ({
	height,
	id,
	instagramLink,
	linkedinLink,
	name1,
	profilePic,
	roles,
	twitterLink,
	width,
	...props
}) => {
	return {
		...props,
		auRGDwIOu: name1 ?? props.auRGDwIOu ?? "Ikta Sollork",
		bA4vGtbKD: instagramLink ?? props.bA4vGtbKD,
		icRgP5hr2: linkedinLink ?? props.icRgP5hr2,
		LtGtTE7gD: twitterLink ?? props.LtGtTE7gD,
		MuqzqmTY8: profilePic ??
			props.MuqzqmTY8 ?? {
				alt: "user pic",
				pixelHeight: 4e3,
				pixelWidth: 4e3,
				src: "https://framerusercontent.com/images/W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg 4000w",
			},
		O2X9vqEVU: roles ?? props.O2X9vqEVU ?? "Web Dev/Developer",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		auRGDwIOu,
		O2X9vqEVU,
		LtGtTE7gD,
		bA4vGtbKD,
		icRgP5hr2,
		MuqzqmTY8,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "tvxPYrVDn",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-prjzlj",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"tvxPYrVDn"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						<motion3.div
							className={"framer-ni9kx8"}
							data-framer-name={"user info"}
							layoutDependency={layoutDependency}
							layoutId={"MoZ5BO3fN"}
						>
							<motion3.div
								className={"framer-ie6soc"}
								data-framer-name={"name"}
								layoutDependency={layoutDependency}
								layoutId={"r65jYfX1n"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-qog2q8"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"rXXgMCQLR"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={auRGDwIOu}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-1kvyxmc"}
											data-styles-preset={"n7RLEGRKm"}
										>
											{"Ikta Sollork"}
										</motion3.p>
									</React3.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-qytrwc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"B3NOa_pP2"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										opacity: 0.6,
									}}
									text={O2X9vqEVU}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion3.p
											className={"framer-styles-preset-1u349i7"}
											data-styles-preset={"rerWrmQ65"}
										>
											{"Web Dev/Developer"}
										</motion3.p>
									</React3.Fragment>
								</RichText>
							</motion3.div>
							<motion3.div
								className={"framer-1ic8fz5"}
								data-framer-name={"socials"}
								layoutDependency={layoutDependency}
								layoutId={"pVrhkF_zx"}
							>
								<Link
									href={LtGtTE7gD}
									motionChild={true}
									nodeId={"QSIYo47mH"}
									scopeId={"rQoyl_iEe"}
								>
									<motion3.a
										className={"framer-a4t2k6 framer-dw0djl"}
										data-framer-name={"Icon"}
										layoutDependency={layoutDependency}
										layoutId={"QSIYo47mH"}
										style={{
											backgroundColor:
												"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
											boxShadow:
												"inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
										}}
									>
										{_jsx3(stdin_default, {
											animated: true,
											className: "framer-95sq5h",
											layoutDependency,
											layoutId: "Au3p9tSSu",
											style: {
												"--1m6trwb": 0,
												"--21h8s6":
													"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
												"--pgex8v": 1.5,
											},
										})}
									</motion3.a>
								</Link>
								<Link
									href={bA4vGtbKD}
									motionChild={true}
									nodeId={"qHOC0nf5t"}
									scopeId={"rQoyl_iEe"}
								>
									<motion3.a
										className={"framer-1ogwg4s framer-dw0djl"}
										data-framer-name={"Icon"}
										layoutDependency={layoutDependency}
										layoutId={"qHOC0nf5t"}
										style={{
											backgroundColor:
												"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
											boxShadow:
												"inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
										}}
									>
										{_jsx3(stdin_default3, {
											animated: true,
											className: "framer-1e87icz",
											layoutDependency,
											layoutId: "FVNAteMbg",
											style: {
												"--1m6trwb": 0,
												"--21h8s6":
													"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
												"--pgex8v": 1.5,
											},
										})}
									</motion3.a>
								</Link>
								<Link
									href={icRgP5hr2}
									motionChild={true}
									nodeId={"XX74HVRPf"}
									scopeId={"rQoyl_iEe"}
								>
									<motion3.a
										className={"framer-71uzei framer-dw0djl"}
										data-framer-name={"Icon"}
										layoutDependency={layoutDependency}
										layoutId={"XX74HVRPf"}
										style={{
											backgroundColor:
												"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
											borderBottomLeftRadius: 8,
											borderBottomRightRadius: 8,
											borderTopLeftRadius: 8,
											borderTopRightRadius: 8,
											boxShadow:
												"inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
										}}
									>
										{_jsx3(stdin_default2, {
											animated: true,
											className: "framer-1xonzyu",
											layoutDependency,
											layoutId: "kfpzP48rq",
											style: {
												"--1m6trwb": 0,
												"--21h8s6":
													"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
												"--pgex8v": 1.5,
											},
										})}
									</motion3.a>
								</Link>
							</motion3.div>
						</motion3.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(32 + ((componentViewport?.height || 200) - 64 - 128) / 2),
								),
								pixelHeight: 4e3,
								pixelWidth: 4e3,
								sizes: `max((${componentViewport?.width || "100vw"} - 89px) / 2, 1px)`,
								...toResponsiveImage(MuqzqmTY8),
							}}
							className={"framer-1wxr9e8"}
							data-framer-name={"pic"}
							layoutDependency={layoutDependency}
							layoutId={"aoFUYpWn3"}
							style={{
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
							}}
						/>
						<motion3.div
							className={"framer-wweawc"}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"OG6k4it7Y"}
							style={{
								background:
									"radial-gradient(50% 50% at 93.7% 8.1%, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)) 0%, rgba(4, 7, 13, 0) 100%)",
								opacity: 0.1,
							}}
						/>
					</motion3.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-eRKLk.framer-dw0djl, .framer-eRKLk .framer-dw0djl { display: block; }",
	".framer-eRKLk.framer-prjzlj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 25px; height: min-content; justify-content: center; overflow: hidden; padding: 32px; position: relative; width: 367px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eRKLk .framer-ni9kx8 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-eRKLk .framer-ie6soc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-eRKLk .framer-qog2q8, .framer-eRKLk .framer-qytrwc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-eRKLk .framer-1ic8fz5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-eRKLk .framer-a4t2k6, .framer-eRKLk .framer-1ogwg4s, .framer-eRKLk .framer-71uzei { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 12px; position: relative; text-decoration: none; width: min-content; }",
	".framer-eRKLk .framer-95sq5h { flex: none; height: var(--framer-aspect-ratio-supported, 17px); position: relative; width: 16px; }",
	".framer-eRKLk .framer-1e87icz, .framer-eRKLk .framer-1xonzyu { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-eRKLk .framer-1wxr9e8 { align-content: center; align-items: center; aspect-ratio: 1.0859375 / 1; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 184px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-eRKLk .framer-wweawc { -webkit-user-select: none; flex: none; height: 306px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; width: 437px; z-index: 1; }",
	...css,
	...css2,
	'.framer-eRKLk[data-border="true"]::after, .framer-eRKLk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerrQoyl_iEe = withCSS3(Component3, css5, "framer-eRKLk");
var stdin_default4 = FramerrQoyl_iEe;
FramerrQoyl_iEe.displayName = "Team card";
FramerrQoyl_iEe.defaultProps = {
	height: 192,
	width: 367,
};
addPropertyControls3(FramerrQoyl_iEe, {
	auRGDwIOu: {
		defaultValue: "Ikta Sollork",
		displayTextArea: false,
		title: "name",
		type: ControlType3.String,
	},
	O2X9vqEVU: {
		defaultValue: "Web Dev/Developer",
		displayTextArea: false,
		title: "roles",
		type: ControlType3.String,
	},
	LtGtTE7gD: {
		title: "twitter link",
		type: ControlType3.Link,
	},
	bA4vGtbKD: {
		title: "instagram link",
		type: ControlType3.Link,
	},
	icRgP5hr2: {
		title: "linkedin link",
		type: ControlType3.Link,
	},
	MuqzqmTY8: {
		__defaultAssetReference:
			"data:framer/asset-reference,W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg?originalFilename=photo-1584999734482-0361aecad844%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwyNnx8cHJvZmlsZSUyMHBpY3xlbnwwfHx8fDE3MzcxNDI3NDl8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "user pic",
			assetReference:
				"data:framer/asset-reference,W7xYkGKzPzvnPv58ZBNzxS3JZI.jpg?originalFilename=photo-1584999734482-0361aecad844%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwyNnx8cHJvZmlsZSUyMHBpY3xlbnwwfHx8fDE3MzcxNDI3NDl8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		},
		title: "profile pic",
		type: ControlType3.ResponsiveImage,
	},
});
addFonts(
	FramerrQoyl_iEe,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...XLogoFonts,
		...InstagramLogoFonts,
		...LinkedinLogoFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var team_card_default = ComponentWithRoot;
export { team_card_default as default };
