// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'Mobile' // Variant
 * version?: string // Version
 * date?: string | Date // Date
 * title?: string // Title
 * intro?: any // Intro
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * link?: string // Link
}} Props

 */
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-R7KDAVHZ.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-D7GXE4AY.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-DE2IIEG7.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-7BNG6VRZ.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-MDFUVCZL.js";
import { className, css, fonts } from "./chunks/chunk-NFCCS2HW.js";
import { routes } from "./chunks/chunk-YOD5Q24P.js";

// virtual:updates-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wy68S4XWzB9EB8hWcxUT/Y0FjBVT1LfHYJGrv3SqS/pTTadvMB0.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleCode,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCodeBoundaryForOverrides,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/MXataBXFUpjeu4LRaOqJ/hWZCFhZKlw5j5AkrF9by/Two_line_wrap.js
import { jsx as _jsx } from "react/jsx-runtime";
function withTwoLineEllipsis(Component3) {
	return (props) => {
		const newStyle = {
			...props.style,
			display: "-webkit-box",
			WebkitBoxOrient: "vertical",
			overflow: "hidden",
			WebkitLineClamp: 2,
			textOverflow: "ellipsis",
		};
		return <Component3 {...props} style={newStyle} />;
	};
}

// /:https://framerusercontent.com/modules/uciMlVFkStsivpDZGG2A/RssFsunWxfKKpsePW2Eg/Htze1ckXM.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter-Bold",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts7 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/jn4BtSPLlS0NDp1KiFAtFKiiY0o.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/g0c8vEViiXNlKAgI4Ymmk3Ig.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css7 = [
	`.framer-ePTKh .framer-styles-preset-nol11v:not(.rich-text-wrapper), .framer-ePTKh .framer-styles-preset-nol11v.rich-text-wrapper h4 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.04em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className7 = "framer-ePTKh";

// /:https://framerusercontent.com/modules/k1nBSTv74HO4Vxlo7dBD/dsBIHo4UwAEINcpfbXTp/lxbrc15NO.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts8 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ksvR4VsLksjpSwnC2fPgHRNMw.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css8 = [
	'.framer-kAkYS .framer-styles-preset-19ljcrl:not(.rich-text-wrapper), .framer-kAkYS .framer-styles-preset-19ljcrl.rich-text-wrapper h1 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 72px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #e4e9f2; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-kAkYS .framer-styles-preset-19ljcrl:not(.rich-text-wrapper), .framer-kAkYS .framer-styles-preset-19ljcrl.rich-text-wrapper h1 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #e4e9f2; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-kAkYS .framer-styles-preset-19ljcrl:not(.rich-text-wrapper), .framer-kAkYS .framer-styles-preset-19ljcrl.rich-text-wrapper h1 { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 48px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: #e4e9f2; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className8 = "framer-kAkYS";

// /:https://framerusercontent.com/modules/NQQMkVr8Sbaqrz7hvyYC/hpCLRetAWpzHgYXNOCrk/Iq1uWtvsr.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-6IDoV";
var variantClassNames = {
	wP1YANO87: "framer-v-1w9ic9x",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, version, width, ...props }) => {
	return {
		...props,
		yxhBO_WVQ: version ?? props.yxhBO_WVQ ?? "Version",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className9,
		layoutId,
		variant,
		yxhBO_WVQ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "wP1YANO87",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1w9ic9x",
							className9,
							classNames,
						)}
						data-framer-name={"primary"}
						layoutDependency={layoutDependency}
						layoutId={"wP1YANO87"}
						ref={ref ?? ref1}
						style={{
							backgroundColor:
								"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-cerpss"}
							data-framer-name={"Category"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"Os75b9bR5"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								"--framer-paragraph-spacing": "0px",
							}}
							text={yxhBO_WVQ}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1kvyxmc"}
									data-styles-preset={"n7RLEGRKm"}
								>
									{"Version"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css9 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6IDoV.framer-1ddp11w, .framer-6IDoV .framer-1ddp11w { display: block; }",
	".framer-6IDoV.framer-1w9ic9x { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 6px 20px 6px 20px; position: relative; width: min-content; }",
	".framer-6IDoV .framer-cerpss { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6IDoV.framer-1w9ic9x { gap: 0px; } .framer-6IDoV.framer-1w9ic9x > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-6IDoV.framer-1w9ic9x > :first-child { margin-top: 0px; } .framer-6IDoV.framer-1w9ic9x > :last-child { margin-bottom: 0px; } }",
	...css,
];
var FramerIq1uWtvsr = withCSS(Component, css9, "framer-6IDoV");
var stdin_default = FramerIq1uWtvsr;
FramerIq1uWtvsr.displayName = "Elements / Version";
FramerIq1uWtvsr.defaultProps = {
	height: 38,
	width: 95,
};
addPropertyControls(FramerIq1uWtvsr, {
	yxhBO_WVQ: {
		defaultValue: "Version",
		title: "Version",
		type: ControlType.String,
	},
});
addFonts(
	FramerIq1uWtvsr,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/wy68S4XWzB9EB8hWcxUT/Y0FjBVT1LfHYJGrv3SqS/pTTadvMB0.js
var ElementsVersionFonts = getFonts(stdin_default);
var RichTextWithTwoLineEllipsisywcz0b = withCodeBoundaryForOverrides(
	RichText2,
	{
		nodeId: "RRFQX4vZG",
		override: withTwoLineEllipsis,
		scopeId: "pTTadvMB0",
	},
);
var RichTextWithTwoLineEllipsispkirv5 = withCodeBoundaryForOverrides(
	RichText2,
	{
		nodeId: "Coyjoq5Ip",
		override: withTwoLineEllipsis,
		scopeId: "pTTadvMB0",
	},
);
var enabledGestures = {
	ADuw6H4mu: {
		hover: true,
	},
};
var cycleOrder = ["ADuw6H4mu", "hedBL0_bB"];
var serializationHash2 = "framer-fHMYB";
var variantClassNames2 = {
	ADuw6H4mu: "framer-v-1dydmzc",
	hedBL0_bB: "framer-v-xnxyux",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var sharedDateFormatter = (value, formatOptions, locale) => {
	if (typeof value !== "string") return "";
	const date = new Date(value);
	if (isNaN(date.getTime())) return "";
	const fallbackLocale = "en-US";
	try {
		return date.toLocaleString(locale || fallbackLocale, formatOptions);
	} catch {
		return date.toLocaleString(fallbackLocale, formatOptions);
	}
};
var dateOptions = {
	dateStyle: "medium",
	timeZone: "UTC",
};
var toDateString = (value, activeLocale) => {
	return sharedDateFormatter(value, dateOptions, activeLocale);
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	desktop: "ADuw6H4mu",
	Mobile: "hedBL0_bB",
};
var getProps2 = ({
	date,
	height,
	id,
	image,
	intro,
	link,
	title,
	version,
	width,
	...props
}) => {
	return {
		...props,
		H6jylDJGn: image ?? props.H6jylDJGn,
		kvdby0rgm: version ?? props.kvdby0rgm ?? "Version",
		RGfB0Q9kA: link ?? props.RGfB0Q9kA,
		TmP3reScl: intro ?? props.TmP3reScl ?? (
			<React2.Fragment>
				<motion2.p>
					{"Performance Update makes opening your Framer projects "}
					<motion2.strong>{"2.5X"}</motion2.strong>
					{" faster and comes with a brand new loading state."}
				</motion2.p>
				<motion2.ul
					style={{
						"--framer-text-alignment": "start",
						"--framer-text-color": "rgb(0, 0, 0)",
						"--framer-text-stroke-color":
							"var(--framer-text-stroke-color, initial)",
						"--framer-text-stroke-width": "0px",
						"--framer-text-transform": "none",
					}}
				>
					<motion2.li
						data-preset-tag={"p"}
						style={{
							"--framer-font-open-type-features": "normal",
							"--framer-font-size": "18px",
							"--framer-letter-spacing": "-0.2px",
							"--framer-line-height": "1.7em",
							"--framer-text-alignment": "left",
							"--framer-text-color":
								"var(--token-289cb3ad-ad59-4cce-aee5-0850b842d9c8, rgba(255, 255, 255, .8))",
							"--framer-text-decoration": "none",
							"--framer-text-stroke-color": "initial",
							"--framer-text-stroke-width": "initial",
							"--framer-text-transform": "none",
						}}
					>
						<motion2.p>
							{"Projects now have much smoother loading states"}
						</motion2.p>
					</motion2.li>
					<motion2.li
						data-preset-tag={"p"}
						style={{
							"--framer-font-open-type-features": "normal",
							"--framer-font-size": "18px",
							"--framer-letter-spacing": "-0.2px",
							"--framer-line-height": "1.7em",
							"--framer-text-alignment": "left",
							"--framer-text-color":
								"var(--token-289cb3ad-ad59-4cce-aee5-0850b842d9c8, rgba(255, 255, 255, .8))",
							"--framer-text-decoration": "none",
							"--framer-text-stroke-color": "initial",
							"--framer-text-stroke-width": "initial",
							"--framer-text-transform": "none",
						}}
					>
						<motion2.p>
							{"Sites become interactive 50% faster than before"}
						</motion2.p>
					</motion2.li>
					<motion2.li
						data-preset-tag={"p"}
						style={{
							"--framer-font-open-type-features": "normal",
							"--framer-font-size": "18px",
							"--framer-letter-spacing": "-0.2px",
							"--framer-line-height": "1.7em",
							"--framer-text-alignment": "left",
							"--framer-text-color":
								"var(--token-289cb3ad-ad59-4cce-aee5-0850b842d9c8, rgba(255, 255, 255, .8))",
							"--framer-text-decoration": "none",
							"--framer-text-stroke-color": "initial",
							"--framer-text-stroke-width": "initial",
							"--framer-text-transform": "none",
						}}
					>
						<motion2.p>
							{"A11Y: In-App Settings can now be tabbed through"}
						</motion2.p>
					</motion2.li>
				</motion2.ul>
			</React2.Fragment>
		),
		Ud0iqyTc_: title ?? props.Ud0iqyTc_ ?? "Title",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ADuw6H4mu",
		ysGdWsZtZ: date ?? props.ysGdWsZtZ ?? "1970-01-01T00:00:00.000Z",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className9,
		layoutId,
		variant,
		kvdby0rgm,
		ysGdWsZtZ,
		Ud0iqyTc_,
		TmP3reScl,
		H6jylDJGn,
		RGfB0Q9kA,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "ADuw6H4mu",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [
		className3,
		className2,
		className8,
		className5,
		className7,
		className6,
		className4,
	];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const activeLocaleCode = useLocaleCode();
	const textContent = toDateString(ysGdWsZtZ, activeLocaleCode);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Link
						href={RGfB0Q9kA}
						motionChild={true}
						nodeId={"ADuw6H4mu"}
						openInNewTab={false}
						scopeId={"pTTadvMB0"}
					>
						<motion2.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-1dydmzc", className9, classNames)} framer-1931z4z`}
							data-border={true}
							data-framer-name={"desktop"}
							layoutDependency={layoutDependency}
							layoutId={"ADuw6H4mu"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								boxShadow: "inset 0px 2px 1px 0px rgba(207, 231, 255, 0.2)",
								...style,
							}}
							{...addPropertyOverrides(
								{
									"ADuw6H4mu-hover": {
										"data-framer-name": void 0,
									},
									hedBL0_bB: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion2.div
								className={"framer-2wc38n"}
								data-framer-name={"content"}
								layoutDependency={layoutDependency}
								layoutId={"YOa5Bj3qm"}
								style={{
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								}}
							>
								<motion2.div
									className={"framer-rpwopa"}
									data-framer-name={"text & others"}
									layoutDependency={layoutDependency}
									layoutId={"qF7iIWF0V"}
								>
									<motion2.div
										className={"framer-1lxw19d"}
										data-framer-name={"version"}
										layoutDependency={layoutDependency}
										layoutId={"qcpy0fSKy"}
									>
										<ComponentViewportProvider
											height={38}
											y={
												(componentViewport?.y || 0) +
												(1 +
													((componentViewport?.height || 759) - 2 - 1188.6) /
														2) +
												48 +
												0 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides(
												{
													"ADuw6H4mu-hover": {
														y:
															(componentViewport?.y || 0) +
															(1 +
																((componentViewport?.height || 756) -
																	2 -
																	1188.6) /
																	2) +
															48 +
															0 +
															0 +
															0 +
															0,
													},
													hedBL0_bB: {
														y:
															(componentViewport?.y || 0) +
															1 +
															0 +
															32 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-4e0ig4-container"}
												layoutDependency={layoutDependency}
												layoutId={"wERZBvJ1D-container"}
												nodeId={"wERZBvJ1D"}
												rendersWithMotion={true}
												scopeId={"pTTadvMB0"}
											>
												{_jsx3(stdin_default, {
													height: "100%",
													id: "wERZBvJ1D",
													layoutId: "wERZBvJ1D",
													width: "100%",
													yxhBO_WVQ: kvdby0rgm,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-1ow0irj"}
											data-framer-name={"Date"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"iHYfTb1YZ"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
												opacity: 0.5,
											}}
											text={textContent}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-qbxcjn"}
													data-styles-preset={"nf0yFfa08"}
												>
													{"Content"}
												</motion2.p>
											</React2.Fragment>
										</RichText2>
									</motion2.div>
									<motion2.div
										className={"framer-1pvwela"}
										data-framer-name={"title & info"}
										layoutDependency={layoutDependency}
										layoutId={"t55d4bOLN"}
									>
										<RichTextWithTwoLineEllipsisywcz0b
											__fromCanvasComponent={true}
											className={"framer-ywcz0b"}
											data-framer-name={"Title"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"RRFQX4vZG"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={Ud0iqyTc_}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.h3
													className={"framer-styles-preset-1y9oj5s"}
													data-styles-preset={"fkjHG1SJt"}
												>
													{"Title"}
												</motion2.h3>
											</React2.Fragment>
										</RichTextWithTwoLineEllipsisywcz0b>
										<RichTextWithTwoLineEllipsispkirv5
											__fromCanvasComponent={true}
											className={"framer-pkirv5"}
											data-framer-name={"Content"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Coyjoq5Ip"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											stylesPresetsClassNames={{
												a: "framer-styles-preset-z4q089",
												code: "framer-styles-preset-1ezv7a4",
												h1: "framer-styles-preset-19ljcrl",
												h2: "framer-styles-preset-6t8r1r",
												h3: "framer-styles-preset-1y9oj5s",
												h4: "framer-styles-preset-nol11v",
												p: "framer-styles-preset-17f5k4v",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											{TmP3reScl}
										</RichTextWithTwoLineEllipsispkirv5>
									</motion2.div>
								</motion2.div>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												(1 +
													((componentViewport?.height || 759) - 2 - 1188.6) /
														2) +
												48 +
												692.6,
										),
										sizes: `calc(max(${componentViewport?.width || "100vw"} - 2px, 1px) - 88px)`,
										...toResponsiveImage(H6jylDJGn),
									}}
									className={"framer-1mymlc"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"mxhvnp9SJ"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									}}
									{...addPropertyOverrides(
										{
											"ADuw6H4mu-hover": {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(1 +
																((componentViewport?.height || 756) -
																	2 -
																	1188.6) /
																	2) +
															48 +
															692.6,
													),
													sizes: `calc(max(${componentViewport?.width || "100vw"} - 2px, 1px) - 88px)`,
													...toResponsiveImage(H6jylDJGn),
												},
											},
											hedBL0_bB: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 1 + 0 + 32 + 692.6,
													),
													sizes: `calc(${componentViewport?.width || "100vw"} - 50px)`,
													...toResponsiveImage(H6jylDJGn),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion2.div>
						</motion2.a>
					</Link>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-fHMYB.framer-1931z4z, .framer-fHMYB .framer-1931z4z { display: block; }",
	".framer-fHMYB.framer-1dydmzc { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 1px; position: relative; text-decoration: none; width: 940px; }",
	".framer-fHMYB .framer-2wc38n { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 48px 44px 48px 44px; position: relative; width: 1px; }",
	".framer-fHMYB .framer-rpwopa { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-fHMYB .framer-1lxw19d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-fHMYB .framer-4e0ig4-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-fHMYB .framer-1ow0irj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-fHMYB .framer-1pvwela { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; max-width: 640px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-fHMYB .framer-ywcz0b, .framer-fHMYB .framer-pkirv5 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-fHMYB .framer-1mymlc { aspect-ratio: 2.15 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 396px); overflow: visible; position: relative; width: 100%; }",
	".framer-fHMYB.framer-v-xnxyux.framer-1dydmzc { align-content: flex-start; align-items: flex-start; cursor: unset; flex-direction: column; width: 390px; }",
	".framer-fHMYB.framer-v-xnxyux .framer-2wc38n { flex: none; padding: 32px 24px 32px 24px; width: 100%; }",
	".framer-fHMYB.framer-v-xnxyux .framer-1lxw19d { order: 0; }",
	".framer-fHMYB.framer-v-xnxyux .framer-1pvwela { order: 1; }",
	".framer-fHMYB.framer-v-xnxyux .framer-1mymlc { height: var(--framer-aspect-ratio-supported, 158px); }",
	...css3,
	...css2,
	...css8,
	...css5,
	...css7,
	...css6,
	...css4,
	'.framer-fHMYB[data-border="true"]::after, .framer-fHMYB [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerpTTadvMB0 = withCSS2(Component2, css10, "framer-fHMYB");
var stdin_default2 = FramerpTTadvMB0;
FramerpTTadvMB0.displayName = "Updates card";
FramerpTTadvMB0.defaultProps = {
	height: 759,
	width: 940,
};
addPropertyControls2(FramerpTTadvMB0, {
	variant: {
		options: ["ADuw6H4mu", "hedBL0_bB"],
		optionTitles: ["desktop", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	kvdby0rgm: {
		defaultValue: "Version",
		title: "Version",
		type: ControlType2.String,
	},
	ysGdWsZtZ: {
		defaultValue: "1970-01-01T00:00:00.000Z",
		title: "Date",
		type: ControlType2.Date,
	},
	Ud0iqyTc_: {
		defaultValue: "Title",
		title: "Title",
		type: ControlType2.String,
	},
	TmP3reScl: {
		defaultValue:
			'<p>Performance Update makes opening your Framer projects <strong>2.5X</strong> faster and comes with a brand new loading state.</p><ul style="--framer-text-color: rgb(0, 0, 0); --framer-text-transform: none; --framer-text-stroke-width: 0px; --framer-text-stroke-color: var(--framer-text-stroke-color, initial); --framer-text-alignment: start;"><li data-preset-tag="p" style="--framer-text-color: var(--token-289cb3ad-ad59-4cce-aee5-0850b842d9c8, rgba(255, 255, 255, .8)); --framer-font-size: 18px; --framer-letter-spacing: -0.2px; --framer-text-transform: none; --framer-text-decoration: none; --framer-text-stroke-width: initial; --framer-text-stroke-color: initial; --framer-font-open-type-features: normal; --framer-line-height: 1.7em; --framer-text-alignment: left;"><p>Projects now have much smoother loading states</p></li><li data-preset-tag="p" style="--framer-text-color: var(--token-289cb3ad-ad59-4cce-aee5-0850b842d9c8, rgba(255, 255, 255, .8)); --framer-font-size: 18px; --framer-letter-spacing: -0.2px; --framer-text-transform: none; --framer-text-decoration: none; --framer-text-stroke-width: initial; --framer-text-stroke-color: initial; --framer-font-open-type-features: normal; --framer-line-height: 1.7em; --framer-text-alignment: left;"><p>Sites become interactive 50% faster than before</p></li><li data-preset-tag="p" style="--framer-text-color: var(--token-289cb3ad-ad59-4cce-aee5-0850b842d9c8, rgba(255, 255, 255, .8)); --framer-font-size: 18px; --framer-letter-spacing: -0.2px; --framer-text-transform: none; --framer-text-decoration: none; --framer-text-stroke-width: initial; --framer-text-stroke-color: initial; --framer-font-open-type-features: normal; --framer-line-height: 1.7em; --framer-text-alignment: left;"><p>A11Y: In-App Settings can now be tabbed through</p></li></ul>',
		description: "",
		title: "Intro",
		type: ControlType2.RichText,
	},
	H6jylDJGn: {
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
	RGfB0Q9kA: {
		title: "Link",
		type: ControlType2.Link,
	},
});
addFonts2(
	FramerpTTadvMB0,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementsVersionFonts,
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts8),
		...getFontsFromSharedStyle2(fonts5),
		...getFontsFromSharedStyle2(fonts7),
		...getFontsFromSharedStyle2(fonts6),
		...getFontsFromSharedStyle2(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:updates-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "hedBL0_bB",
	xl: "ADuw6H4mu",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders UpdatesCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var updates_card_default = ComponentWithRoot;
export { updates_card_default as default };
