// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary' | 'Primary hower' // Variant
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-ZFADYJLF.js";
import {
	NullState,
	defaultEvents,
	useIconSelection,
} from "../chunks/chunk-NULYBL27.js";
import { routes } from "../chunks/chunk-YOD5Q24P.js";

// virtual:elements/read-more
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/t8uSmKHD3Ql5rNXoXCRt/Nc55TQmNyfsbWEci9q46/Ykj3oY6N0.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { useState, useEffect, useRef } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";

// /:https://framerusercontent.com/modules/8tFVJ9SCM5akQRM0UzVD/YkxZV5bKC4LrRDEdvAgQ/home.js
var r;
var s = (o) => {
	if (!r) {
		const n = o.forwardRef(
			({ color: t = "currentColor", size: e = 24, ...i }, l) => {
				return o.createElement(
					"svg",
					{
						ref: l,
						xmlns: "http://www.w3.org/2000/svg",
						width: e,
						height: e,
						viewBox: "0 0 24 24",
						fill: "none",
						stroke: t,
						strokeWidth: "2",
						strokeLinecap: "round",
						strokeLinejoin: "round",
						...i,
					},
					o.createElement("path", {
						d: "M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
					}),
					o.createElement("polyline", {
						points: "9 22 9 12 15 12 15 22",
					}),
				);
			},
		);
		(n.displayName = "Home"), (r = n);
	}
	return r;
};

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
var iconKeys = [
	"activity",
	"airplay",
	"alert-circle",
	"alert-octagon",
	"alert-triangle",
	"align-center",
	"align-justify",
	"align-left",
	"align-right",
	"anchor",
	"aperture",
	"archive",
	"arrow-down",
	"arrow-down-circle",
	"arrow-down-left",
	"arrow-down-right",
	"arrow-left",
	"arrow-left-circle",
	"arrow-right",
	"arrow-right-circle",
	"arrow-up",
	"arrow-up-circle",
	"arrow-up-left",
	"arrow-up-right",
	"at-sign",
	"award",
	"bar-chart",
	"bar-chart-2",
	"battery",
	"battery-charging",
	"bell",
	"bell-off",
	"bluetooth",
	"bold",
	"book",
	"book-open",
	"bookmark",
	"box",
	"briefcase",
	"calendar",
	"camera",
	"camera-off",
	"cast",
	"check",
	"check-circle",
	"check-square",
	"chevron-down",
	"chevron-left",
	"chevron-right",
	"chevron-up",
	"chevrons-down",
	"chevrons-left",
	"chevrons-right",
	"chevrons-up",
	"chrome",
	"circle",
	"clipboard",
	"clock",
	"cloud",
	"cloud-drizzle",
	"cloud-lightning",
	"cloud-off",
	"cloud-rain",
	"cloud-snow",
	"code",
	"codepen",
	"codesandbox",
	"coffee",
	"columns",
	"command",
	"compass",
	"copy",
	"corner-down-left",
	"corner-down-right",
	"corner-left-down",
	"corner-left-up",
	"corner-right-down",
	"corner-right-up",
	"corner-up-left",
	"corner-up-right",
	"cpu",
	"credit-card",
	"crop",
	"crosshair",
	"database",
	"delete",
	"disc",
	"divide",
	"divide-circle",
	"divide-square",
	"dollar-sign",
	"download",
	"download-cloud",
	"dribbble",
	"droplet",
	"edit",
	"edit-2",
	"edit-3",
	"external-link",
	"eye",
	"eye-off",
	"facebook",
	"fast-forward",
	"feather",
	"figma",
	"file",
	"file-minus",
	"file-plus",
	"file-text",
	"film",
	"filter",
	"flag",
	"folder",
	"folder-minus",
	"folder-plus",
	"framer",
	"frown",
	"gift",
	"git-branch",
	"git-commit",
	"git-merge",
	"git-pull-request",
	"github",
	"gitlab",
	"globe",
	"grid",
	"hard-drive",
	"hash",
	"headphones",
	"heart",
	"help-circle",
	"hexagon",
	"home",
	"image",
	"inbox",
	"info",
	"instagram",
	"italic",
	"key",
	"layers",
	"layout",
	"life-buoy",
	"link",
	"link-2",
	"linkedin",
	"list",
	"loader",
	"lock",
	"log-in",
	"log-out",
	"mail",
	"map",
	"map-pin",
	"maximize",
	"maximize-2",
	"meh",
	"menu",
	"message-circle",
	"message-square",
	"mic",
	"mic-off",
	"minimize",
	"minimize-2",
	"minus",
	"minus-circle",
	"minus-square",
	"monitor",
	"moon",
	"more-horizontal",
	"more-vertical",
	"mouse-pointer",
	"move",
	"music",
	"navigation",
	"navigation-2",
	"octagon",
	"package",
	"paperclip",
	"pause",
	"pause-circle",
	"pen-tool",
	"percent",
	"phone",
	"phone-call",
	"phone-forwarded",
	"phone-incoming",
	"phone-missed",
	"phone-off",
	"phone-outgoing",
	"pie-chart",
	"play",
	"play-circle",
	"plus",
	"plus-circle",
	"plus-square",
	"pocket",
	"power",
	"printer",
	"radio",
	"refresh-ccw",
	"refresh-cw",
	"repeat",
	"rewind",
	"rotate-ccw",
	"rotate-cw",
	"rss",
	"save",
	"scissors",
	"search",
	"send",
	"server",
	"settings",
	"share",
	"share-2",
	"shield",
	"shield-off",
	"shopping-bag",
	"shopping-cart",
	"shuffle",
	"sidebar",
	"skip-back",
	"skip-forward",
	"slack",
	"slash",
	"sliders",
	"smartphone",
	"smile",
	"speaker",
	"square",
	"star",
	"stop-circle",
	"sun",
	"sunrise",
	"sunset",
	"tablet",
	"tag",
	"target",
	"terminal",
	"thermometer",
	"thumbs-down",
	"thumbs-up",
	"toggle-left",
	"toggle-right",
	"tool",
	"trash",
	"trash-2",
	"trello",
	"trending-down",
	"trending-up",
	"triangle",
	"truck",
	"tv",
	"twitch",
	"twitter",
	"type",
	"umbrella",
	"underline",
	"unlock",
	"upload",
	"upload-cloud",
	"user",
	"user-check",
	"user-minus",
	"user-plus",
	"user-x",
	"users",
	"video",
	"video-off",
	"voicemail",
	"volume",
	"volume-1",
	"volume-2",
	"volume-x",
	"watch",
	"wifi",
	"wifi-off",
	"wind",
	"x",
	"x-circle",
	"x-octagon",
	"x-square",
	"youtube",
	"zap",
	"zap-off",
	"zoom-in",
	"zoom-out",
];
var moduleBaseUrl = "https://framer.com/m/feather-icons/";
var uppercaseIconKeys = iconKeys.map(
	(name) => name.charAt(0).toUpperCase() + name.slice(1),
);
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? s(React) : null,
	);
	async function importModule() {
		let active = true;
		try {
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@0.0.29`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (active) setSelectedIcon(module.default(React));
		} catch (e) {
			console.log(e);
			if (active) setSelectedIcon(null);
		}
		return () => {
			active = false;
		};
	}
	useEffect(() => {
		importModule();
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<SelectedIcon
					style={{
						width: "100%",
						height: "100%",
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					color={color}
				/>
			) : (
				emptyState
			)}
		</div>
	);
}
Icon.displayName = "Feather";
Icon.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "home",
	iconSearch: "Home",
	color: "#66F",
	selectByList: true,
	mirrored: false,
};
addPropertyControls(Icon, {
	selectByList: {
		type: ControlType.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType.Enum,
		options: iconKeys,
		optionTitles: uppercaseIconKeys,
		defaultValue: Icon.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Feather site](https://feathericons.com/)",
	},
	iconSearch: {
		type: ControlType.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	mirrored: {
		type: ControlType.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon.defaultProps.mirrored,
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: Icon.defaultProps.color,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/t8uSmKHD3Ql5rNXoXCRt/Nc55TQmNyfsbWEci9q46/Ykj3oY6N0.js
var FeatherFonts = getFonts(Icon);
var cycleOrder = ["pQbd7enxy", "kfrl7DZ6O"];
var serializationHash = "framer-gk14w";
var variantClassNames = {
	kfrl7DZ6O: "framer-v-igzkix",
	pQbd7enxy: "framer-v-5s7o13",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React2.Fragment);
var humanReadableVariantMap = {
	"Primary hower": "kfrl7DZ6O",
	Primary: "pQbd7enxy",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "pQbd7enxy",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "pQbd7enxy",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-5s7o13",
							className2,
							classNames,
						)}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"pQbd7enxy"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								kfrl7DZ6O: {
									"data-framer-name": "Primary hower",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ojq3nw"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"lrXsqClHt"}
							style={{
								"--framer-link-text-color": "rgb(162, 148, 255)",
								"--framer-link-text-decoration": "none",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion.p
									className={"framer-styles-preset-dmuy5d"}
									data-styles-preset={"LC6TE31cM"}
								>
									{"Read more"}
								</motion.p>
							</React2.Fragment>
						</RichText>
						<motion.div
							className={"framer-2i0hnt"}
							data-framer-name={"Arrow"}
							layoutDependency={layoutDependency}
							layoutId={"bMt8crZwK"}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1if6wbk-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"KnA1ZzEW9-container"}
									nodeId={"KnA1ZzEW9"}
									rendersWithMotion={true}
									scopeId={"Ykj3oY6N0"}
								>
									<Icon
										color={
											"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))"
										}
										height={"100%"}
										iconSearch={"Home"}
										iconSelection={"chevron-right"}
										id={"KnA1ZzEW9"}
										layoutId={"KnA1ZzEW9"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion.div
								className={"framer-11p7uqj"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"NVM_SB1OK"}
								style={{
									backgroundColor:
										"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
									borderBottomLeftRadius: 1,
									borderBottomRightRadius: 1,
									borderTopLeftRadius: 1,
									borderTopRightRadius: 1,
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gk14w.framer-53xmqf, .framer-gk14w .framer-53xmqf { display: block; }",
	".framer-gk14w.framer-5s7o13 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 26px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 120px; }",
	".framer-gk14w .framer-1ojq3nw { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }",
	".framer-gk14w .framer-2i0hnt { flex: none; height: 14px; overflow: visible; position: relative; width: 34px; }",
	".framer-gk14w .framer-1if6wbk-container { bottom: -4px; flex: none; height: 20px; position: absolute; right: 6px; width: 36px; }",
	".framer-gk14w .framer-11p7uqj { flex: none; height: 2px; left: 12px; overflow: visible; position: absolute; top: calc(57.14285714285716% - 2px / 2); width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-gk14w.framer-5s7o13 { gap: 0px; } .framer-gk14w.framer-5s7o13 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-gk14w.framer-5s7o13 > :first-child { margin-left: 0px; } .framer-gk14w.framer-5s7o13 > :last-child { margin-right: 0px; } }",
	".framer-gk14w.framer-v-igzkix .framer-1if6wbk-container { right: -13px; }",
	".framer-gk14w.framer-v-igzkix .framer-11p7uqj { width: 19px; }",
	...css,
];
var FramerYkj3oY6N0 = withCSS(Component, css2, "framer-gk14w");
var stdin_default = FramerYkj3oY6N0;
FramerYkj3oY6N0.displayName = "Elements / Read More";
FramerYkj3oY6N0.defaultProps = {
	height: 26,
	width: 120,
};
addPropertyControls2(FramerYkj3oY6N0, {
	variant: {
		options: ["pQbd7enxy", "kfrl7DZ6O"],
		optionTitles: ["Primary", "Primary hower"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerYkj3oY6N0,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:elements/read-more
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ReadMoreFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var read_more_default = ComponentWithRoot;
export { read_more_default as default };
