// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Playing' | 'Complete' | 'Inactive' // Variant
 * title?: string // Title
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-YLF6WDSY.js";
import { routes } from "../chunks/chunk-YOD5Q24P.js";

// virtual:component/step
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/khIk4vWchyVkq8nshBtL/ZrNtsKCgMqFI8QEAQZIL/kp3q5qt1W.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	b88z41vz_: {
		hover: true,
	},
};
var cycleOrder = ["rObxpNGp_", "zNzyWdzz3", "b88z41vz_"];
var serializationHash = "framer-dg50c";
var variantClassNames = {
	b88z41vz_: "framer-v-stukul",
	rObxpNGp_: "framer-v-409wy3",
	zNzyWdzz3: "framer-v-prt7qe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Complete: "zNzyWdzz3",
	Inactive: "b88z41vz_",
	Playing: "rObxpNGp_",
};
var getProps = ({ click, height, id, title, width, ...props }) => {
	return {
		...props,
		dDnGYdLN4: title ?? props.dDnGYdLN4 ?? "STEP 1",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "rObxpNGp_",
		vYMcHT6Mz: click ?? props.vYMcHT6Mz,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		dDnGYdLN4,
		vYMcHT6Mz,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "rObxpNGp_",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1k1ht34 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (vYMcHT6Mz) {
			const res = await vYMcHT6Mz(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-409wy3",
							className2,
							classNames,
						)}
						data-framer-name={"Playing"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"rObxpNGp_"}
						onTap={onTap1k1ht34}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-f213e283-24d0-40a3-a2dc-bca1da07b971, rgb(16, 19, 28))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							boxShadow: "inset 0px 1px 1px 0px rgba(207, 231, 255, 0.2)",
							...style,
						}}
						variants={{
							"b88z41vz_-hover": {
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))",
							},
						}}
						{...addPropertyOverrides(
							{
								"b88z41vz_-hover": {
									"data-framer-name": void 0,
								},
								b88z41vz_: {
									"data-framer-name": "Inactive",
								},
								zNzyWdzz3: {
									"data-framer-name": "Complete",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1gekb2v"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"X7vL8UOYi"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={dDnGYdLN4}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1u349i7"}
									data-styles-preset={"rerWrmQ65"}
								>
									{"STEP 1"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dg50c.framer-19oxzmg, .framer-dg50c .framer-19oxzmg { display: block; }",
	".framer-dg50c.framer-409wy3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; overflow: hidden; padding: 13px; position: relative; width: 134px; will-change: var(--framer-will-change-override, transform); }",
	".framer-dg50c .framer-1gekb2v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var Framerkp3q5qt1W = withCSS(Component, css2, "framer-dg50c");
var stdin_default = Framerkp3q5qt1W;
Framerkp3q5qt1W.displayName = "Component / Step";
Framerkp3q5qt1W.defaultProps = {
	height: 44,
	width: 134,
};
addPropertyControls(Framerkp3q5qt1W, {
	variant: {
		options: ["rObxpNGp_", "zNzyWdzz3", "b88z41vz_"],
		optionTitles: ["Playing", "Complete", "Inactive"],
		title: "Variant",
		type: ControlType.Enum,
	},
	dDnGYdLN4: {
		defaultValue: "STEP 1",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	vYMcHT6Mz: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Framerkp3q5qt1W,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:component/step
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "b88z41vz_",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StepFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var step_default = ComponentWithRoot;
export { step_default as default };
