#!/usr/bin/env python3
"""Health check: assert the audit_log_no_update trigger is enabled.

The trigger enforces audit_log row immutability — a SOC 2 load-bearing
control. Two call sites legitimately disable it briefly to denormalize
agent_name into audit rows before purge (see api/app/routers/admin.py,
common/queries/user_cleanup.py); both wrap the disable in try/finally
so it always gets re-enabled. This check is defense in depth: it
catches a future regression where try/finally gets removed, a bug
that already fired in prod and left it disabled, a manual psql disable
that's never re-enabled, or any new call site added without proper
guarding.

Read-only. Does NOT attempt to re-enable the trigger — alert only.

Exit codes:
  0  trigger enabled (or briefing already posted for today)
  1  trigger DISABLED or missing — audit-log immutability not enforced
  2  config / connection error

Usage:
    DATABASE_URL=postgresql://... \\
    CEO_API_KEY=... \\
    python3 scripts/check_audit_trigger.py
    python3 scripts/check_audit_trigger.py --dry-run
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys
from json import dumps, loads
from urllib import error as uerror
from urllib import request as ureq

import psycopg2

API_BASE = os.environ.get("CEO_API_URL", "https://ceo-agent-evfb.onrender.com")
COMPANY = "ai-identity"
TAG_PREFIX = "auto:audit-trigger-health"

CHECK_SQL = """
    SELECT tgenabled
    FROM pg_trigger
    WHERE tgname = 'audit_log_no_update'
      AND tgrelid = 'audit_log'::regclass
"""

ALERT_TITLE = "🚨 audit_log_no_update trigger is DISABLED"
ALERT_BODY = (
    "**audit_log_no_update trigger is DISABLED — audit-log immutability "
    "is currently NOT enforced. Investigate immediately.**\n\n"
    "This trigger blocks UPDATE on `audit_log` rows and is a SOC 2 "
    "load-bearing control. Two call sites in the API legitimately disable "
    "it briefly (`api/app/routers/admin.py`, `common/queries/user_cleanup.py`) "
    "and re-enable it in `finally`. If this alert fired, one of:\n\n"
    "1. A bug left the trigger disabled (try/finally got skipped or removed).\n"
    "2. A manual `psql` disable was never re-enabled.\n"
    "3. A new call site disables the trigger without proper guarding.\n\n"
    "**To re-enable** (after confirming no purge is in flight):\n"
    "```sql\n"
    "ALTER TABLE audit_log ENABLE TRIGGER audit_log_no_update;\n"
    "```\n\n"
    "Then audit `audit_log` rows updated since the last known good state "
    "(see `audit_log.prev_hash` / integrity chain) for tampering.\n\n"
    "_Auto-generated by `scripts/check_audit_trigger.py` "
    "(`.github/workflows/audit-trigger-health.yml`)_"
)
MISSING_BODY = (
    "**audit_log_no_update trigger is MISSING from the database.**\n\n"
    "Expected to find a trigger named `audit_log_no_update` on table "
    "`audit_log` (created by migration "
    "`a1b2c3d4e5f6_add_audit_integrity_chain.py`). The trigger blocks "
    "UPDATEs on audit rows and is a SOC 2 load-bearing control.\n\n"
    "Either the migration has not been applied, the trigger was dropped "
    "manually, or this check is pointed at the wrong database. "
    "Investigate immediately.\n\n"
    "_Auto-generated by `scripts/check_audit_trigger.py`._"
)


def _request(method: str, path: str, body: dict | None = None):
    key = os.environ.get("CEO_API_KEY")
    if not key:
        print("WARN: CEO_API_KEY not set — skipping briefing post", file=sys.stderr)
        return None
    url = f"{API_BASE}{path}"
    data = dumps(body).encode() if body is not None else None
    req = ureq.Request(
        url,
        data=data,
        method=method,
        headers={"X-API-Key": key, "Content-Type": "application/json"},
    )
    try:
        with ureq.urlopen(req, timeout=20) as r:
            return loads(r.read())
    except uerror.HTTPError as e:
        print(
            f"WARN: {method} {path} -> HTTP {e.code}: {e.read().decode()[:300]}",
            file=sys.stderr,
        )
        return None
    except OSError as e:
        print(f"WARN: {method} {path} failed: {e}", file=sys.stderr)
        return None


def _post_briefing_idempotent(title: str, body: str, today_tag: str) -> None:
    recent = _request("GET", f"/api/v1/briefings?company={COMPANY}&limit=20")
    for b in recent or []:
        if today_tag in (b.get("tags") or []):
            print(f"✓ briefing already posted for today (id #{b['id']}) — not reposting")
            return
    payload = {
        "company_slug": COMPANY,
        "title": title,
        "body": body,
        "author": "security",
        "tags": [today_tag, "audit-trigger-health", "soc2"],
    }
    res = _request("POST", "/api/v1/briefings", payload)
    if res is not None:
        print(f"✓ briefing posted (id #{res.get('id', '?')})")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true", help="check only, don't post briefing")
    args = p.parse_args()

    dsn = os.environ.get("DATABASE_URL")
    if not dsn:
        print("ERROR: DATABASE_URL not set", file=sys.stderr)
        return 2

    try:
        conn = psycopg2.connect(dsn, connect_timeout=15)
        conn.set_session(readonly=True, autocommit=True)
        with conn.cursor() as cur:
            cur.execute(CHECK_SQL)
            row = cur.fetchone()
        conn.close()
    except psycopg2.Error as e:
        print(f"ERROR: DB connection / query failed: {e}", file=sys.stderr)
        return 2

    today_tag = f"{TAG_PREFIX}:{dt.date.today().isoformat()}"

    if row is None:
        # Trigger does not exist.
        print("FAIL: audit_log_no_update trigger NOT FOUND on audit_log", file=sys.stderr)
        if not args.dry_run:
            _post_briefing_idempotent(
                "🚨 audit_log_no_update trigger MISSING", MISSING_BODY, today_tag
            )
        return 1

    tgenabled = row[0]
    # pg_trigger.tgenabled: 'O' = origin (enabled), 'D' = disabled,
    # 'R' = replica, 'A' = always. Only 'D' is the failure case.
    if tgenabled == "D":
        print(
            "FAIL: audit_log_no_update trigger is DISABLED "
            "— audit-log immutability is currently NOT enforced",
            file=sys.stderr,
        )
        if not args.dry_run:
            _post_briefing_idempotent(ALERT_TITLE, ALERT_BODY, today_tag)
        return 1

    print(f"✓ audit_log_no_update trigger is enabled (tgenabled={tgenabled!r})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
