#!/usr/bin/env python3
"""Sweep for active decisions whose review_date has passed.

Posts ONE summary briefing per day if there are stale decisions —
silent (no briefing posted) when everything is current. Severity
tiered by days overdue:
  mild     1-3 days past review
  moderate 4-14 days past review
  severe   15+ days past review

Also flags active decisions that have no review_date set at all —
lower priority but a real gap (no scheduled review = no follow-through).
Those only show up in the briefing if there's at least one stale row;
they don't trigger a briefing on their own.

Idempotent: tag-dedupes against any briefing already posted with
today's date. Re-running mid-day is a no-op.

Usage:
    CEO_API_KEY=... python3 scripts/sweep_stale_decisions.py
    python3 scripts/sweep_stale_decisions.py --dry-run
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys
from json import dumps, loads
from pathlib import Path
from urllib import error as uerror
from urllib import request as ureq

API_BASE = os.environ.get("CEO_API_URL", "https://ceo-agent-evfb.onrender.com")
COMPANY = "ai-identity"
TAG_PREFIX = "auto:stale-decisions"


def _api_key() -> str:
    key = os.environ.get("CEO_API_KEY")
    if key:
        return key
    env = Path.home() / "Dev" / "CEO-Dashboard" / "backend" / ".env"
    if env.exists():
        for line in env.read_text().splitlines():
            if line.startswith("CEO_API_KEY="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    sys.exit("ERROR: CEO_API_KEY not set")


def _request(method: str, path: str, body: dict | None = None):
    url = f"{API_BASE}{path}"
    data = dumps(body).encode() if body is not None else None
    req = ureq.Request(
        url,
        data=data,
        method=method,
        headers={"X-API-Key": _api_key(), "Content-Type": "application/json"},
    )
    try:
        with ureq.urlopen(req, timeout=20) as r:
            return loads(r.read())
    except uerror.HTTPError as e:
        sys.exit(f"ERROR: {method} {path} -> HTTP {e.code}: {e.read().decode()[:300]}")


def _severity(days_overdue: int) -> str:
    if days_overdue >= 15:
        return "severe"
    if days_overdue >= 4:
        return "moderate"
    return "mild"


def _build_briefing_body(stale: list[dict], no_date: list[dict], now_ts: int) -> str:
    today = dt.date.today().isoformat()
    severe = [d for d in stale if _severity(d["days_overdue"]) == "severe"]
    moderate = [d for d in stale if _severity(d["days_overdue"]) == "moderate"]
    mild = [d for d in stale if _severity(d["days_overdue"]) == "mild"]

    lines = [
        f"## Stale decisions sweep — {today}",
        "",
        f"**{len(stale)} active decision(s) past their review_date.** "
        f"Severe (15+d): {len(severe)} · Moderate (4-14d): {len(moderate)} · Mild (1-3d): {len(mild)}",
        "",
    ]

    def section(title: str, rows: list[dict]) -> list[str]:
        if not rows:
            return []
        out = [f"### {title}", ""]
        for d in rows:
            rd = dt.datetime.fromtimestamp(d["review_date"]).strftime("%Y-%m-%d")
            out.append(f"- **#{d['id']}** _{rd} ({d['days_overdue']}d ago)_ — {d['title']}")
        out.append("")
        return out

    lines += section("🔴 Severe — review immediately or re-baseline", severe)
    lines += section("🟠 Moderate — review this week", moderate)
    lines += section("🟡 Mild — review when convenient", mild)

    if no_date:
        lines += [
            "### ℹ️ Active decisions with no review_date set",
            "_Not stale, but no scheduled review means no follow-through. Set a review_date or close the decision._",
            "",
        ]
        for d in no_date:
            lines.append(f"- **#{d['id']}** — {d['title']}")
        lines.append("")

    lines += [
        "**To clear a stale decision:** PUT `/api/v1/decisions/{id}` with either "
        "(a) a new `review_date` if more time is needed, or "
        '(b) `status: "decided"` if the call has been made and follow-through is in flight.',
        "",
        "_Auto-generated by `scripts/sweep_stale_decisions.py`_",
    ]
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    today_iso = dt.date.today().isoformat()
    today_tag = f"{TAG_PREFIX}:{today_iso}"
    now_ts = int(dt.datetime.now().timestamp())

    # Idempotency check first — skip the API churn if we've already posted today
    if not args.dry_run:
        recent = _request("GET", f"/api/v1/briefings?company={COMPANY}&limit=20")
        for b in recent or []:
            if today_tag in (b.get("tags") or []):
                print(f"✓ briefing for {today_iso} already posted (id #{b['id']}) — skipping")
                return

    decisions = _request("GET", f"/api/v1/decisions?company={COMPANY}&status=active")

    stale: list[dict] = []
    no_date: list[dict] = []
    for d in decisions:
        rd = d.get("review_date")
        if rd is None:
            no_date.append(d)
        elif rd < now_ts:
            d["days_overdue"] = (now_ts - rd) // 86400
            stale.append(d)
    stale.sort(key=lambda x: x["days_overdue"], reverse=True)

    print(f"▶ Active decisions: {len(decisions)}")
    print(f"  Stale: {len(stale)}  ·  No review_date: {len(no_date)}")
    for d in stale:
        rd = dt.datetime.fromtimestamp(d["review_date"]).strftime("%Y-%m-%d")
        print(
            f"    #{d['id']} {rd} ({d['days_overdue']}d) [{_severity(d['days_overdue']):8}] {d['title'][:60]}"
        )

    if not stale:
        print("✅ No stale decisions — silent (no briefing posted).")
        return

    body = _build_briefing_body(stale, no_date, now_ts)
    if args.dry_run:
        print("--- briefing body (DRY) ---")
        print(body)
        return

    payload = {
        "company_slug": COMPANY,
        "title": f"Stale decisions sweep — {today_iso}",
        "body": body,
        "author": "pm",
        "tags": [today_tag, "stale-review"],
    }
    _request("POST", "/api/v1/briefings", payload)
    print(f"✓ briefing posted for {today_iso}")


if __name__ == "__main__":
    main()
