// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5d5a53b2b7b03258 "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'navl ink' | 'footer link' // Variant
 * link?: string // Link
 * title?: string // Title
 * tap?: Function // Tap
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-ZFADYJLF.js";
import { routes } from "../chunks/chunk-YOD5Q24P.js";

// virtual:nav/nav-link
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/s5fQ24C0qLkP3oNjeji3/raYusrZsUYtwu193DWkc/wbHw6LNvF.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	oWIL6ezID: {
		hover: true,
	},
	sRAT6dzdP: {
		hover: true,
	},
};
var cycleOrder = ["sRAT6dzdP", "oWIL6ezID"];
var serializationHash = "framer-EEc8p";
var variantClassNames = {
	oWIL6ezID: "framer-v-1le2i5b",
	sRAT6dzdP: "framer-v-p5j5qq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"footer link": "oWIL6ezID",
	"navl ink": "sRAT6dzdP",
};
var getProps = ({ height, id, link, tap, title, width, ...props }) => {
	return {
		...props,
		fF32h_OBQ: title ?? props.fF32h_OBQ ?? "Link",
		kwWR1ZLuI: tap ?? props.kwWR1ZLuI,
		Mm9yYAj7D: link ?? props.Mm9yYAj7D,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "sRAT6dzdP",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Mm9yYAj7D,
		fF32h_OBQ,
		kwWR1ZLuI,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "sRAT6dzdP",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTaplhzzwy = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (kwWR1ZLuI) {
			const res = await kwWR1ZLuI(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={Mm9yYAj7D}
						motionChild={true}
						nodeId={"sRAT6dzdP"}
						scopeId={"wbHw6LNvF"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-p5j5qq", className2, classNames)} framer-om04cv`}
							data-framer-name={"navl ink"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"sRAT6dzdP"}
							onTap={onTaplhzzwy}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"oWIL6ezID-hover": {
										"data-framer-name": void 0,
									},
									"sRAT6dzdP-hover": {
										"data-framer-name": void 0,
									},
									oWIL6ezID: {
										"data-framer-name": "footer link",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1l9jozo"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Ts60qAvtL"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255))",
									opacity: 0.75,
								}}
								text={fF32h_OBQ}
								variants={{
									"oWIL6ezID-hover": {
										"--extracted-r6o4lv":
											"var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255))",
									},
									"sRAT6dzdP-hover": {
										opacity: 1,
									},
									oWIL6ezID: {
										"--extracted-r6o4lv":
											"var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7))",
										opacity: 1,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"oWIL6ezID-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-dmuy5d"}
														data-styles-preset={"LC6TE31cM"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255)))",
														}}
													>
														{"Link"}
													</motion.p>
												</React.Fragment>
											),
										},
										oWIL6ezID: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-dmuy5d"}
														data-styles-preset={"LC6TE31cM"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)))",
														}}
													>
														{"Link"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-dmuy5d"}
										data-styles-preset={"LC6TE31cM"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255)))",
										}}
									>
										{"Link"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EEc8p.framer-om04cv, .framer-EEc8p .framer-om04cv { display: block; }",
	".framer-EEc8p.framer-p5j5qq { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 6px 12px 6px 12px; position: relative; text-decoration: none; width: min-content; }",
	".framer-EEc8p .framer-1l9jozo { -webkit-user-select: none; flex: none; height: auto; overflow: visible; position: relative; user-select: none; white-space: pre; width: auto; z-index: 1; }",
	".framer-EEc8p.framer-v-1le2i5b.framer-p5j5qq { padding: 6px 0px 6px 0px; }",
	...css,
];
var FramerwbHw6LNvF = withCSS(Component, css2, "framer-EEc8p");
var stdin_default = FramerwbHw6LNvF;
FramerwbHw6LNvF.displayName = "Nav / Nav Link";
FramerwbHw6LNvF.defaultProps = {
	height: 34,
	width: 51,
};
addPropertyControls(FramerwbHw6LNvF, {
	variant: {
		options: ["sRAT6dzdP", "oWIL6ezID"],
		optionTitles: ["navl ink", "footer link"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Mm9yYAj7D: {
		title: "Link",
		type: ControlType.Link,
	},
	fF32h_OBQ: {
		defaultValue: "Link",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	kwWR1ZLuI: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerwbHw6LNvF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav/nav-link
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "sRAT6dzdP",
	xl: "oWIL6ezID",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavLinkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5d5a53b2b7b032585e2eef6b3d726ef8a269c27380483119104364b744dd4fb2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var nav_link_default = ComponentWithRoot;
export { nav_link_default as default };
